import React, { useState, useEffect } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ArrowLeft, Save } from 'lucide-react';
import { Module, Panel } from '@/utils/apiService';
import IconSelector from './IconSelector';

interface ApiModuleFormProps {
  module?: Module | null;
  panels: Panel[];
  onSubmit: (data: any) => void;
  onCancel: () => void;
}

const ApiModuleForm = ({ module, panels, onSubmit, onCancel }: ApiModuleFormProps) => {
  const [formData, setFormData] = useState({
    panel_id: '',
    title: '',
    slug: '',
    description: '',
    icon: 'Package',
    color: '#6366f1',
    price: '0.00',
    cost_price: '0.00',
    path: '',
    category: 'general',
    operational_status: 'on' as 'on' | 'off' | 'maintenance',
    is_active: 1,
    is_premium: 0,
    api_endpoint: '',
    api_method: 'POST' as 'GET' | 'POST' | 'PUT' | 'DELETE',
    sort_order: '0',
    settings: '{}'
  });

  const [slugAutoGenerated, setSlugAutoGenerated] = useState(true);

  useEffect(() => {
    if (module) {
      console.log('🔄 [API_MODULE_FORM] Carregando dados do módulo para edição:', module);
      
      setFormData({
        panel_id: module.panel_id?.toString() || '',
        title: module.title || '',
        slug: module.slug || '',
        description: module.description || '',
        icon: module.icon || 'Package',
        color: module.color || '#6366f1',
        price: module.price?.toString() || '0.00',
        cost_price: module.cost_price?.toString() || '0.00',
        path: module.path || '',
        category: module.category || 'general',
        operational_status: module.operational_status || 'on',
        is_active: module.is_active ? 1 : 0,
        is_premium: module.is_premium ? 1 : 0,
        api_endpoint: module.api_endpoint || '',
        api_method: (module.api_method as 'GET' | 'POST' | 'PUT' | 'DELETE') || 'POST',
        sort_order: module.sort_order?.toString() || '0',
        settings: typeof module.settings === 'object' ? JSON.stringify(module.settings) : (module.settings || '{}')
      });
      setSlugAutoGenerated(false);
    }
  }, [module]);

  const generateSlug = (title: string) => {
    return title
      .toLowerCase()
      .normalize('NFD')
      .replace(/[\u0300-\u036f]/g, '')
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .trim();
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    
    console.log('🔄 [API_MODULE_FORM] ===== INICIANDO SUBMISSÃO =====');
    console.log('📋 [API_MODULE_FORM] Dados do formulário:', formData);
    
    // Validações obrigatórias
    if (!formData.title.trim()) {
      console.error('❌ [API_MODULE_FORM] Título é obrigatório');
      alert('Título é obrigatório');
      return;
    }
    
    if (!formData.panel_id) {
      console.error('❌ [API_MODULE_FORM] Painel é obrigatório');
      alert('Painel é obrigatório');
      return;
    }

    // Gerar slug final se necessário
    let finalSlug = formData.slug.trim();
    if (!finalSlug && formData.title) {
      finalSlug = generateSlug(formData.title);
      console.log('🔄 [API_MODULE_FORM] Slug gerado automaticamente:', finalSlug);
    }

    if (!finalSlug) {
      console.error('❌ [API_MODULE_FORM] Slug é obrigatório');
      alert('Slug é obrigatório');
      return;
    }

    // Preparar dados EXATAMENTE como a tabela modules espera
    const moduleData = {
      // Campos obrigatórios da tabela
      panel_id: parseInt(formData.panel_id, 10),
      name: formData.title.trim(), // Campo name necessário para a interface
      title: formData.title.trim(),
      slug: finalSlug,
      
      // Campos opcionais com valores corretos conforme a tabela
      description: formData.description.trim() || null,
      icon: formData.icon || 'Package',
      color: formData.color || '#6366f1',
      price: parseFloat(formData.price) || 0.00,
      cost_price: parseFloat(formData.cost_price) || 0.00,
      path: formData.path.trim() || null,
      category: formData.category || 'general',
      operational_status: formData.operational_status || 'on',
      is_active: Boolean(formData.is_active), // Converter para boolean
      is_premium: Boolean(formData.is_premium), // Converter para boolean
      api_endpoint: formData.api_endpoint.trim() || null,
      api_method: formData.api_method || 'POST',
      sort_order: parseInt(formData.sort_order) || 0,
      settings: formData.settings || '{}'
    };

    console.log('📤 [API_MODULE_FORM] Dados estruturados para API:', moduleData);
    console.log('📊 [API_MODULE_FORM] Tipos dos campos:', {
      panel_id: `${moduleData.panel_id} (${typeof moduleData.panel_id})`,
      name: `"${moduleData.name}" (${typeof moduleData.name})`,
      title: `"${moduleData.title}" (${typeof moduleData.title})`,
      slug: `"${moduleData.slug}" (${typeof moduleData.slug})`,
      price: `${moduleData.price} (${typeof moduleData.price})`,
      is_active: `${moduleData.is_active} (${typeof moduleData.is_active})`,
      is_premium: `${moduleData.is_premium} (${typeof moduleData.is_premium})`
    });
    
    // Enviar para o hook
    console.log('🚀 [API_MODULE_FORM] Enviando dados para o hook...');
    onSubmit(moduleData);
  };

  const handleChange = (field: string, value: any) => {
    console.log(`🔄 [API_MODULE_FORM] Campo alterado: ${field} = ${value}`);
    
    setFormData(prev => {
      const newData = { ...prev, [field]: value };
      
      // Auto-gerar slug apenas para novos módulos
      if (field === 'title' && slugAutoGenerated && !module) {
        const newSlug = generateSlug(value);
        newData.slug = newSlug;
        console.log(`🔄 [API_MODULE_FORM] Slug auto-gerado: ${newSlug}`);
      }
      
      return newData;
    });
  };

  const handleSlugChange = (value: string) => {
    console.log('🔄 [API_MODULE_FORM] Slug editado manualmente:', value);
    setSlugAutoGenerated(false);
    handleChange('slug', value);
  };

  return (
    <div className="w-full max-w-4xl mx-auto">
      <Card className="w-full">
        <CardHeader>
          <div className="flex items-center gap-4">
            <Button variant="ghost" size="sm" onClick={onCancel}>
              <ArrowLeft className="h-4 w-4" />
            </Button>
            <CardTitle>
              {module ? 'Editar Módulo' : 'Novo Módulo'}
            </CardTitle>
          </div>
        </CardHeader>
        <CardContent className="w-full">
          <form onSubmit={handleSubmit} className="w-full space-y-6">
            {/* Linha 1: Painel e Título */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="w-full">
                <Label htmlFor="panel_id">Painel *</Label>
                <Select value={formData.panel_id} onValueChange={(value) => handleChange('panel_id', value)} required>
                  <SelectTrigger className="w-full">
                    <SelectValue placeholder="Selecione um painel" />
                  </SelectTrigger>
                  <SelectContent>
                    {panels.map((panel) => (
                      <SelectItem key={panel.id} value={panel.id.toString()}>
                        {panel.name}
                      </SelectItem>
                    ))}
                  </SelectContent>
                </Select>
              </div>

              <div className="w-full">
                <Label htmlFor="title">Título *</Label>
                <Input
                  id="title"
                  value={formData.title}
                  onChange={(e) => handleChange('title', e.target.value)}
                  placeholder="Título do módulo"
                  className="w-full"
                  required
                />
              </div>
            </div>

            {/* Linha 2: Slug e Categoria */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="w-full">
                <Label htmlFor="slug">URL Slug *</Label>
                <Input
                  id="slug"
                  value={formData.slug}
                  onChange={(e) => handleSlugChange(e.target.value)}
                  placeholder="URL amigável"
                  className="w-full"
                  required
                />
                <p className="text-xs text-gray-500 mt-1">
                  {slugAutoGenerated && !module ? 'Gerado automaticamente' : 'Editado manualmente'}
                </p>
              </div>

              <div className="w-full">
                <Label htmlFor="category">Categoria</Label>
                <Select value={formData.category} onValueChange={(value) => handleChange('category', value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="general">Geral</SelectItem>
                    <SelectItem value="consultas">Consultas</SelectItem>
                    <SelectItem value="premium">Premium</SelectItem>
                    <SelectItem value="relatorios">Relatórios</SelectItem>
                    <SelectItem value="veiculos">Veículos</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Descrição */}
            <div className="w-full">
              <Label htmlFor="description">Descrição</Label>
              <Textarea
                id="description"
                value={formData.description}
                onChange={(e) => handleChange('description', e.target.value)}
                placeholder="Descrição do módulo"
                rows={3}
                className="w-full resize-none"
              />
            </div>

            {/* Linha 3: Ícone e Cor */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="w-full">
                <IconSelector
                  value={formData.icon}
                  onChange={(value) => handleChange('icon', value)}
                  label="Ícone do Módulo"
                />
              </div>

              <div className="w-full">
                <Label htmlFor="color">Cor</Label>
                <Input
                  id="color"
                  type="color"
                  value={formData.color}
                  onChange={(e) => handleChange('color', e.target.value)}
                  className="w-full h-10"
                />
              </div>
            </div>

            {/* Linha 4: Preços */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="w-full">
                <Label htmlFor="price">Preço de Venda</Label>
                <Input
                  id="price"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.price}
                  onChange={(e) => handleChange('price', e.target.value)}
                  placeholder="0.00"
                  className="w-full"
                />
              </div>

              <div className="w-full">
                <Label htmlFor="cost_price">Preço de Custo</Label>
                <Input
                  id="cost_price"
                  type="number"
                  step="0.01"
                  min="0"
                  value={formData.cost_price}
                  onChange={(e) => handleChange('cost_price', e.target.value)}
                  placeholder="0.00"
                  className="w-full"
                />
              </div>
            </div>

            {/* Linha 5: API Endpoint e Método */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="w-full">
                <Label htmlFor="api_endpoint">Link da página do módulo</Label>
                <Input
                  id="api_endpoint"
                  value={formData.api_endpoint}
                  onChange={(e) => handleChange('api_endpoint', e.target.value)}
                  placeholder="/dashboard/consultar-cpf-simples"
                  className="w-full"
                />
                <p className="text-xs text-gray-600 dark:text-gray-400 mt-1">
                  Informe a rota interna do módulo (ex.: <span className="font-mono">/dashboard/consultar-cpf-puxa-tudo</span>).
                </p>
              </div>

              <div className="w-full">
                <Label htmlFor="api_method">Método HTTP</Label>
                <Select value={formData.api_method} onValueChange={(value) => handleChange('api_method', value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="GET">GET</SelectItem>
                    <SelectItem value="POST">POST</SelectItem>
                    <SelectItem value="PUT">PUT</SelectItem>
                    <SelectItem value="DELETE">DELETE</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </div>

            {/* Status e Configurações */}
            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              <div className="w-full">
                <Label htmlFor="operational_status">Status Operacional</Label>
                <Select value={formData.operational_status} onValueChange={(value) => handleChange('operational_status', value)}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="on">Ativo</SelectItem>
                    <SelectItem value="off">Inativo</SelectItem>
                    <SelectItem value="maintenance">Manutenção</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="w-full">
                <Label htmlFor="is_active">Status Geral</Label>
                <Select value={formData.is_active.toString()} onValueChange={(value) => handleChange('is_active', parseInt(value))}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="1">Ativo</SelectItem>
                    <SelectItem value="0">Inativo</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="w-full">
                <Label htmlFor="is_premium">Tipo de Plano</Label>
                <Select value={formData.is_premium.toString()} onValueChange={(value) => handleChange('is_premium', parseInt(value))}>
                  <SelectTrigger className="w-full">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="0">Básico</SelectItem>
                    <SelectItem value="1">Premium</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div className="w-full">
                <Label htmlFor="sort_order">Ordem de Exibição</Label>
                <Input
                  id="sort_order"
                  type="number"
                  min="0"
                  value={formData.sort_order}
                  onChange={(e) => handleChange('sort_order', e.target.value)}
                  placeholder="0"
                  className="w-full"
                />
              </div>
            </div>

            {/* Botões de Ação */}
            <div className="flex flex-col sm:flex-row gap-3 pt-4 w-full border-t">
              <Button type="submit" className="flex items-center justify-center gap-2 w-full sm:w-auto">
                <Save className="h-4 w-4" />
                {module ? 'Atualizar Módulo' : 'Criar Módulo'}
              </Button>
              <Button type="button" variant="outline" onClick={onCancel} className="w-full sm:w-auto">
                Cancelar
              </Button>
            </div>
          </form>
        </CardContent>
      </Card>
    </div>
  );
};

export default ApiModuleForm;
