
import React, { useState, useMemo } from 'react';
import { Label } from "@/components/ui/label";
import { Button } from "@/components/ui/button";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  Package, Search, User, Building, Car, FileText, Shield, TrendingUp, 
  Camera, Phone, Mail, MapPin, Heart, Star, Calendar, Clock, 
  Settings, Database, Cloud, Lock, Key, Eye, Download, Upload,
  BarChart, PieChart, LineChart, Edit, Trash, Plus, Check, X,
  Home, Globe, Zap, Target, Award, Gift, Flag, Bell, MessageCircle,
  Activity, Briefcase, Calculator, CreditCard, DollarSign, Fingerprint,
  Folder, HardDrive, Headphones, Image, Laptop, Layers, Link, Map,
  Percent, Printer, Smartphone, Wrench, Truck, Wallet, Wifi, Users,
  History, AlertCircle, Anchor, Archive, ArrowUpRight, Atom, BadgeCheck, 
  Banknote, Battery, Bluetooth, Bookmark, Box, Brain, Bug, Cake, 
  CircleDollarSign, Clipboard, Code, Compass, Cpu, Crown, Diamond, Disc, 
  Drama, Dribbble, Drum, Eraser, Facebook, Feather, Film, Filter, Flame, 
  FlaskConical, Gamepad2, Gauge, Gem, Github, Glasses, GraduationCap, 
  Hammer, Hash, Hexagon, Instagram, Joystick, Keyboard, Landmark, LayoutGrid, 
  Lightbulb, Linkedin, Magnet, Megaphone, Microscope, Monitor, Moon, Mountain,
  Music, Network, Newspaper, Paintbrush, Palette, Paperclip, PenTool,
  Pizza, Plane, Plug, Podcast, Puzzle, QrCode, Radio, Rocket,
  Ruler, Scale, Scissors, Server, Share2, ShieldCheck, ShoppingBag,
  ShoppingCart, Signpost, Slack, Smile, Sparkles, Speaker, Stethoscope,
  Sun, Sword, Tag, Telescope, Terminal, ThumbsUp, Timer, ToggleLeft,
  Trophy, Tv, Umbrella, Video, Voicemail, Volume2, Watch, Wind, Youtube,
  // Novos ícones para chegar a 500+
  Accessibility, AirVent, Airplay, AlarmCheck, AlarmClock, AlarmMinus, AlarmPlus,
  Album, AlertOctagon, AlertTriangle, AlignCenter, AlignJustify, AlignLeft, AlignRight,
  Ampersand, Angry, Annoyed, Antenna, Aperture, Apple, ArchiveRestore, ArchiveX,
  Armchair, ArrowBigDown, ArrowBigLeft, ArrowBigRight, ArrowBigUp, ArrowDown,
  ArrowDownCircle, ArrowDownLeft, ArrowDownRight, ArrowDownToLine, ArrowLeft,
  ArrowLeftCircle, ArrowLeftRight, ArrowLeftToLine, ArrowRight, ArrowRightCircle,
  ArrowRightLeft, ArrowRightToLine, ArrowUp, ArrowUpCircle, ArrowUpDown,
  ArrowUpLeft, ArrowUpToLine, ArrowsUpFromLine, Asterisk, AtSign,
  AudioLines, AudioWaveform, Axe, Baby, Backpack, BadgeAlert, BadgeCent,
  BadgeDollarSign, BadgeEuro, BadgeHelp, BadgeIndianRupee, BadgeInfo, BadgeJapaneseYen,
  BadgeMinus, BadgePercent, BadgePlus, BadgePoundSterling, BadgeRussianRuble,
  BadgeSwissFranc, BadgeX, BaggageClaim, Banana, Bandage, Barcode, Baseline,
  Bath, BatteryCharging, BatteryFull, BatteryLow, BatteryMedium, BatteryWarning,
  Beaker, Bean, BeanOff, Bed, BedDouble, BedSingle, Beef, Beer, BellDot,
  BellMinus, BellOff, BellPlus, BellRing, BetweenHorizontalEnd, BetweenHorizontalStart,
  BetweenVerticalEnd, BetweenVerticalStart, Bike, Binary, Binoculars, Biohazard,
  Bird, Bitcoin, Blend, Blinds, Blocks, BluetoothConnected, BluetoothOff,
  BluetoothSearching, Bold, Bomb, Bone, Book, BookA, BookAudio, BookCheck,
  BookCopy, BookDashed, BookDown, BookHeadphones, BookHeart, BookImage, BookKey,
  BookLock, BookMarked, BookMinus, BookOpen, BookOpenCheck, BookOpenText, BookPlus,
  BookText, BookType, BookUp, BookUser, BookX, Bot, BotMessageSquare,
  Boxes, Braces, BrainCircuit, BrainCog, BrickWall, Briefcase as BriefcaseBusiness,
  BringToFront, Brush, BugOff, BugPlay, Building2, BusFront, Cable, CableCar,
  CakeSlice, CalculatorIcon, CalendarCheck, CalendarCheck2, CalendarClock, CalendarDays,
  CalendarHeart, CalendarMinus, CalendarOff, CalendarPlus, CalendarRange, CalendarSearch,
  CalendarX, CalendarX2, CameraOff, Candy, CandyCane, CandyOff, Cannabis, Captions,
  CaptionsOff, CarFront, CarTaxiFront, Caravan, Carrot, CaseLower, CaseSensitive,
  CaseUpper, Cast, Castle, Cat, ChartArea, ChartBar, ChartBarBig, ChartBarDecreasing,
  ChartBarIncreasing, ChartBarStacked, ChartCandlestick, ChartColumn,
  ChartColumnBig, ChartColumnDecreasing, ChartColumnIncreasing, ChartColumnStacked,
  ChartGantt, ChartLine, ChartNetwork, ChartNoAxesColumn, ChartNoAxesCombined,
  ChartNoAxesGantt, ChartPie, ChartScatter, ChartSpline, CheckCheck, CheckCircle,
  CheckCircle2, CheckSquare, ChefHat, Cherry, ChevronDown, ChevronFirst,
  ChevronLast, ChevronLeft, ChevronRight, ChevronUp, ChevronsDown,
  ChevronsDownUp, ChevronsLeft, ChevronsLeftRight, ChevronsRight, ChevronsRightLeft,
  ChevronsUp, ChevronsUpDown, Chrome, Church, Cigarette, CigaretteOff, Circle,
  CircleAlert, CircleArrowDown, CircleArrowLeft, CircleArrowOutDownLeft,
  CircleArrowOutDownRight, CircleArrowOutUpLeft, CircleArrowOutUpRight,
  CircleArrowRight, CircleArrowUp, CircleCheck, CircleCheckBig, CircleDashed,
  CircleDivide, CircleDot, CircleDotDashed, CircleEllipsis, CircleEqual,
  CircleFadingPlus, CircleGauge, CircleHelp, CircleMinus, CircleOff, CircleParking,
  CircleParkingOff, CirclePause, CirclePercent, CirclePlay, CirclePlus, CirclePower,
  CircleSlash, CircleSlash2, CircleStop, CircleUser, CircleUserRound, CircleX,
  CircuitBoard, Citrus, Clapperboard, ClipboardCheck, ClipboardCopy, ClipboardList,
  ClipboardMinus, ClipboardPaste, ClipboardPen, ClipboardPlus, ClipboardType,
  ClipboardX, ClockAlert, Clock1, Clock10, Clock11, Clock12, Clock2, Clock3,
  Clock4, Clock5, Clock6, Clock7, Clock8, Clock9, CloudCog, CloudDownload,
  CloudDrizzle, CloudFog, CloudHail, CloudLightning, CloudMoon, CloudMoonRain,
  CloudOff, CloudRain, CloudRainWind, CloudSnow, CloudSun, CloudSunRain, CloudUpload,
  Cloudy, Clover, Club, CodeSquare, CodeXml, Codepen, Codesandbox, Coffee, Cog,
  Coins, Columns2, Columns3, Columns4, Combine, Command, Compass as CompassIcon,
  Component, Computer, ConciergeBell, Cone, Construction, Contact, ContactRound,
  Container, Contrast, Cookie, CookingPot, Copy, CopyCheck, CopyMinus, CopyPlus,
  CopySlash, CopyX, Copyleft, Copyright, CornerDownLeft, CornerDownRight,
  CornerLeftDown, CornerLeftUp, CornerRightDown, CornerRightUp, CornerUpLeft,
  CornerUpRight, Croissant, Crop, Cross, Crosshair, CupSoda, Currency, Cylinder,
  Database as DatabaseIcon, DatabaseBackup, DatabaseZap, Delete, Dessert, Diameter,
  DiamondMinus, DiamondPercent, DiamondPlus, Dice1, Dice2, Dice3, Dice4, Dice5, Dice6,
  Dices, Diff, Disc2, Disc3, DiscAlbum, Divide, DnaOff, Dna, Dock, Dog,
  DoorClosed, DoorOpen, Dot, Download as DownloadIcon, DownloadCloud, DraftingCompass,
  Drama as DramaIcon, Droplet, Droplets, Drumstick, Dumbbell, Ear, EarOff, Eclipse,
  EggFried, EggOff, Egg, Ellipsis, EllipsisVertical, Equal, EqualNot, EqualSquare,
  EraserIcon, Euro, Expand, ExternalLink, EyeOff, Factory, Fan, FastForward,
  Fence, FerrisWheel, Figma, File, FileArchive, FileAudio, FileAudio2, FileAxis3d,
  FileBadge, FileBadge2, FileBarChart, FileBarChart2, FileBox, FileCheck, FileCheck2,
  FileClock, FileCode, FileCode2, FileCog, FileDiff, FileDigit, FileDown, FileHeart,
  FileImage, FileInput, FileJson, FileJson2, FileKey, FileKey2, FileLineChart,
  FileLock, FileLock2, FileMinus, FileMinus2, FileMusic, FileOutput, FilePen,
  FilePenLine, FilePieChart, FilePlus, FilePlus2, FileQuestion, FileScan, FileSearch,
  FileSearch2, FileSignature, FileSliders, FileSpreadsheet, FileStack, FileSymlink,
  FileTerminal, FileType, FileType2, FileUp, FileVideo, FileVideo2, FileVolume,
  FileVolume2, FileWarning, FileX, FileX2, Files, Film as FilmIcon, Fingerprint as FingerprintIcon,
  FireExtinguisher, Fish, FishOff, FishSymbol, Flag as FlagIcon, FlagOff, FlagTriangleLeft,
  FlagTriangleRight, FlameKindling, Flashlight, FlashlightOff, FlaskConical as FlaskConicalIcon,
  FlaskRound, FlipHorizontal, FlipHorizontal2, FlipVertical, FlipVertical2, Flower,
  Flower2, Focus, FoldHorizontal, FoldVertical, Folder as FolderIcon, FolderArchive,
  FolderCheck, FolderClock, FolderClosed, FolderCog, FolderDot, FolderDown,
  FolderGit, FolderGit2, FolderHeart, FolderInput, FolderKanban, FolderKey,
  FolderLock, FolderMinus, FolderOpen, FolderOpenDot, FolderOutput, FolderPen,
  FolderPlus, FolderRoot, FolderSearch, FolderSearch2, FolderSymlink, FolderSync,
  FolderTree, FolderUp, FolderX, Folders, Footprints, Forklift, Forward, Frame,
  Framer, Frown, Fuel, Fullscreen, GalleryHorizontal, GalleryHorizontalEnd,
  GalleryThumbnails, GalleryVertical, GalleryVerticalEnd, Gamepad, Gauge as GaugeIcon,
  Gavel, Gem as GemIcon, Ghost, Gift as GiftIcon, GitBranch, GitBranchPlus, GitCommitHorizontal,
  GitCommitVertical, GitCompare, GitCompareArrows, GitFork, GitGraph, GitMerge,
  GitPullRequest, GitPullRequestArrow, GitPullRequestClosed, GitPullRequestCreate,
  GitPullRequestDraft, Gitlab, GlassWater, Glasses as GlassesIcon, Globe as GlobeIcon, Globe2,
  GlobeLock, Goal, Grab, GraduationCap as GraduationCapIcon, Grape, Grid2x2, Grid2x2Check,
  Grid2x2Plus, Grid2x2X, Grid3x3, Grip, GripHorizontal, GripVertical, Group,
  Guitar, Ham, Hammer as HammerIcon, Hand, HandCoins, HandHeart, HandHelping, HandMetal,
  HandPlatter, Handshake, HardDrive as HardDriveIcon, HardDriveDownload, HardDriveUpload,
  HardHat, Hash as HashIcon, Haze, HdmiPort, Heading, Heading1, Heading2, Heading3,
  Heading4, Heading5, Heading6, HeadphoneOff, Headphones as HeadphonesIcon, Headset,
  Heart as HeartIcon, HeartCrack, HeartHandshake, HeartOff, HeartPulse, Heater,
  Hexagon as HexagonIcon, Highlighter, History as HistoryIcon, Hop, HopOff, Hospital,
  Hotel, Hourglass, House, HousePlug, HousePlus, IceCream, IceCreamBowl, IceCreamCone,
  IdCard, Image as ImageIcon, ImageDown, ImageMinus, ImageOff, ImagePlay, ImagePlus,
  ImageUp, Images, Import, Inbox, Indent, IndentDecrease, IndentIncrease,
  IndianRupee, Infinity, Info, InspectionPanel, Instagram as InstagramIcon, Italic,
  IterationCcw, IterationCw, JapaneseYen, Kanban, Key as KeyIcon, KeyRound, KeySquare,
  Keyboard as KeyboardIcon, KeyboardMusic, KeyboardOff, Lamp, LampCeiling, LampDesk,
  LampFloor, LampWallDown, LampWallUp, LandPlot, Landmark as LandmarkIcon, Languages,
  Laptop as LaptopIcon, Laptop2, LaptopMinimal, Lasso, LassoSelect, Laugh, Layers as LayersIcon,
  Layers2, Layers3, LayoutDashboard, LayoutGrid as LayoutGridIcon, LayoutList, LayoutPanelLeft,
  LayoutPanelTop, LayoutTemplate, Leaf, LeafyGreen, Lectern, LetterText, Library,
  LibraryBig, LifeBuoy, Ligature, Lightbulb as LightbulbIcon, LightbulbOff, Link as LinkIcon, Link2,
  Link2Off, Linkedin as LinkedinIcon, List, ListCheck, ListChecks, ListCollapse, ListEnd,
  ListFilter, ListMinus, ListMusic, ListOrdered, ListPlus, ListRestart, ListStart,
  ListTodo, ListTree, ListVideo, ListX, Loader, Loader2, LoaderCircle, LoaderPinwheel,
  Locate, LocateFixed, LocateOff, Lock as LockIcon, LockKeyhole, LockKeyholeOpen, LockOpen,
  LogIn, LogOut, Logs, Lollipop, Luggage, Magnet as MagnetIcon, Mail as MailIcon, MailCheck,
  MailMinus, MailOpen, MailPlus, MailQuestion, MailSearch, MailWarning, MailX, Mailbox,
  Mails, Map as MapIcon, MapPin as MapPinIcon, MapPinCheck, MapPinCheckInside, MapPinHouse, MapPinMinus,
  MapPinMinusInside, MapPinOff, MapPinPlus, MapPinPlusInside, MapPinX, MapPinXInside,
  MapPinned, Martini, Maximize, Maximize2, Medal, Megaphone as MegaphoneIcon, Meh, MemoryStick,
  Menu, Merge, MessageCircle as MessageCircleIcon, MessageCircleCode, MessageCircleDashed,
  MessageCircleHeart, MessageCircleMore, MessageCircleOff, MessageCirclePlus,
  MessageCircleQuestion, MessageCircleReply, MessageCircleWarning, MessageCircleX,
  MessageSquare, MessageSquareCode, MessageSquareDashed, MessageSquareDiff,
  MessageSquareDot, MessageSquareHeart, MessageSquareLock, MessageSquareMore,
  MessageSquareOff, MessageSquarePlus, MessageSquareQuote, MessageSquareReply,
  MessageSquareShare, MessageSquareText, MessageSquareWarning, MessageSquareX,
  MessagesSquare, Mic, Mic2, MicOff, MicVocal, Microchip, Microscope as MicroscopeIcon,
  Microwave, Milestone, Milk, MilkOff, Minimize, Minimize2, Minus, MinusCircle,
  MinusSquare, Monitor as MonitorIcon, MonitorCheck, MonitorCog, MonitorDot, MonitorDown,
  MonitorOff, MonitorPause, MonitorPlay, MonitorSmartphone, MonitorSpeaker, MonitorStop,
  MonitorUp, MonitorX, Moon as MoonIcon, MoonStar, MoreHorizontal, MoreVertical,
  Mountain as MountainIcon, MountainSnow, Mouse, MouseOff, MousePointer, MousePointer2,
  MousePointerBan, MousePointerClick, Move, Move3d, MoveDiagonal, MoveDiagonal2,
  MoveDown, MoveDownLeft, MoveDownRight, MoveHorizontal, MoveLeft, MoveRight,
  MoveUp, MoveUpLeft, MoveUpRight, MoveVertical, Music as MusicIcon, Music2, Music3, Music4,
  Navigation, Navigation2, NavigationOff, Network as NetworkIcon, Nfc, NotebookPen,
  NotebookTabs, NotebookText, NotepadText, NotepadTextDashed, Nut, OctagonAlert,
  OctagonMinus, OctagonPause, OctagonX, Option, Orbit, Origami, Package as PackageIcon,
  Package2, PackageCheck, PackageMinus, PackageOpen, PackagePlus, PackageSearch,
  PackageX, PaintBucket, PaintRoller, Paintbrush as PaintbrushIcon, Paintbrush2, Palette as PaletteIcon,
  PanelBottom, PanelBottomClose, PanelBottomDashed, PanelBottomOpen, PanelLeft,
  PanelLeftClose, PanelLeftDashed, PanelLeftOpen, PanelRight, PanelRightClose,
  PanelRightDashed, PanelRightOpen, PanelTop, PanelTopClose, PanelTopDashed,
  PanelTopOpen, PanelsLeftBottom, PanelsRightBottom, PanelsTopLeft, Paperclip as PaperclipIcon,
  Parentheses, ParkingMeter, PartyPopper, Pause, PauseCircle, PawPrint, PcCase, Pen,
  PenLine, PenOff, PenTool as PenToolIcon, Pencil, PencilLine, PencilOff, PencilRuler, Pentagon,
  Percent as PercentIcon, PercentCircle, PercentDiamond, PercentSquare, PersonStanding,
  PhilippinePeso, Phone as PhoneIcon, PhoneCall, PhoneForwarded, PhoneIncoming, PhoneMissed,
  PhoneOff, PhoneOutgoing, Pi, PiSquare, Piano, Pickaxe, PictureInPicture, PictureInPicture2,
  PiggyBank, Pilcrow, PilcrowLeft, PilcrowRight, PilcrowSquare, Pill, PillBottle, Pin,
  PinOff, Pipette, Pizza as PizzaIcon, Plane as PlaneIcon, PlaneLanding, PlaneTakeoff, Play, PlayCircle,
  PlaySquare, Plug as PlugIcon, Plug2, PlugZap, PlugZap2, Plus as PlusIcon, PlusCircle, PlusSquare,
  Pocket, PocketKnife, Podcast as PodcastIcon, Pointer, PointerOff, Popcorn, Popsicle, PoundSterling,
  Power, PowerCircle, PowerOff, PowerSquare, Presentation, Printer as PrinterIcon, Projector,
  Proportions, Puzzle as PuzzleIcon, Pyramid, QrCode as QrCodeIcon, Quote, Rabbit, Radar, Radiation,
  Radical, Radio as RadioIcon, RadioReceiver, RadioTower, Radius, RailSymbol, Rainbow, Rat, Ratio,
  Receipt, ReceiptCent, ReceiptEuro, ReceiptIndianRupee, ReceiptJapaneseYen, ReceiptPoundSterling,
  ReceiptRussianRuble, ReceiptSwissFranc, ReceiptText, RectangleEllipsis, RectangleHorizontal,
  RectangleVertical, Recycle, Redo, Redo2, RefreshCcw, RefreshCcwDot, RefreshCw, RefreshCwOff,
  Refrigerator, Regex, RemoveFormatting, Repeat, Repeat1, Repeat2, Replace, ReplaceAll, Reply,
  ReplyAll, Rewind, Ribbon, Rocket as RocketIcon, RockingChair, RollerCoaster, Rotate3d, RotateCcw,
  RotateCcwSquare, RotateCw, RotateCwSquare, Route, RouteOff, Router, Rows2, Rows3, Rows4, Rss,
  Ruler as RulerIcon, RussianRuble, Sailboat, Salad, Sandwich, Satellite, SatelliteDish, Save, SaveAll,
  SaveOff, Scale as ScaleIcon, Scale3d, Scaling, Scan, ScanBarcode, ScanEye, ScanFace, ScanLine,
  ScanQrCode, ScanSearch, ScanText, ScatterChart, School, School2, Scissors as ScissorsIcon,
  ScissorsLineDashed, ScissorsSquare, ScissorsSquareDashedBottom, ScreenShare, ScreenShareOff,
  Scroll, ScrollText, Search as SearchIcon, SearchCheck, SearchCode, SearchSlash, SearchX, Section,
  Send, SendHorizontal, SendToBack, SeparatorHorizontal, SeparatorVertical, Server as ServerIcon,
  ServerCog, ServerCrash, ServerOff, Settings as SettingsIcon, Settings2, Shapes, Share, Share2 as Share2Icon,
  Sheet, Shell, Shield as ShieldIcon, ShieldAlert, ShieldBan, ShieldCheck as ShieldCheckIcon, ShieldEllipsis,
  ShieldHalf, ShieldMinus, ShieldOff, ShieldPlus, ShieldQuestion, ShieldX, Ship, ShipWheel,
  Shirt, ShoppingBag as ShoppingBagIcon, ShoppingBasket, ShoppingCart as ShoppingCartIcon, Shovel, ShowerHead,
  Shrink, Shrub, Shuffle, Sidebar, SidebarClose, SidebarOpen, Sigma, Signal, SignalHigh, SignalLow,
  SignalMedium, SignalZero, Signature, Signpost as SignpostIcon, SignpostBig, Siren, SkipBack, SkipForward,
  Skull, Slack as SlackIcon, Slash, Slice, SlidersHorizontal, SlidersVertical, Smartphone as SmartphoneIcon,
  SmartphoneCharging, SmartphoneNfc, Smile as SmileIcon, SmilePlus, Snail, Snowflake, Sofa, SortAsc,
  SortDesc, Soup, Space, Spade, Sparkle, Sparkles as SparklesIcon, Speaker as SpeakerIcon, Speech, SpellCheck,
  SpellCheck2, Spline, Split, SprayCan, Sprout, Square, SquareActivity, SquareArrowDown,
  SquareArrowDownLeft, SquareArrowDownRight, SquareArrowLeft, SquareArrowOutDownLeft,
  SquareArrowOutDownRight, SquareArrowOutUpLeft, SquareArrowOutUpRight, SquareArrowRight,
  SquareArrowUp, SquareArrowUpLeft, SquareArrowUpRight, SquareAsterisk, SquareBottomDashedScissors,
  SquareChartGantt, SquareCheck, SquareCheckBig, SquareChevronDown, SquareChevronLeft,
  SquareChevronRight, SquareChevronUp, SquareCode, SquareDashedBottom, SquareDashedBottomCode,
  SquareDashedKanban, SquareDashedMousePointer, SquareDivide, SquareDot, SquareEqual,
  SquareFunction, SquareGanttChart, SquareKanban, SquareLibrary, SquareM, SquareMenu,
  SquareMinus, SquareMousePointer, SquareParking, SquareParkingOff, SquarePen, SquarePercent,
  SquarePi, SquarePilcrow, SquarePlay, SquarePlus, SquarePower, SquareRadical, SquareScissors,
  SquareSigma, SquareSlash, SquareSplitHorizontal, SquareSplitVertical, SquareSquare, SquareStack,
  SquareTerminal, SquareUser, SquareUserRound, SquareX, Squircle, Squirrel, Stamp, Star as StarIcon,
  StarHalf, StarOff, StepBack, StepForward, Stethoscope as StethoscopeIcon, Sticker, StickyNote, Store,
  StretchHorizontal, StretchVertical, Strikethrough, Subscript, Sun as SunIcon, SunDim, SunMedium,
  SunMoon, SunSnow, Sunrise, Sunset, Superscript, SwatchBook, SwissFranc, SwitchCamera, Sword as SwordIcon,
  Swords, Syringe, Table, Table2, TableCellsMerge, TableCellsSplit, TableColumnsSplit,
  TableOfContents, TableProperties, TableRowsSplit, Tablet, TabletSmartphone, Tablets, Tag as TagIcon,
  Tags, Tally1, Tally2, Tally3, Tally4, Tally5, Tangent, Target as TargetIcon, Telescope as TelescopeIcon, Tent,
  TentTree, Terminal as TerminalIcon, TerminalSquare, TestTube, TestTube2, TestTubes, Text, TextCursor,
  TextCursorInput, TextQuote, TextSearch, TextSelect, Theater, Thermometer, ThermometerSnowflake,
  ThermometerSun, ThumbsDown, ThumbsUp as ThumbsUpIcon, Ticket, TicketCheck, TicketMinus, TicketPercent,
  TicketPlus, TicketSlash, TicketX, TicketsPlane, Timer as TimerIcon, TimerOff, TimerReset, ToggleLeft as ToggleLeftIcon,
  ToggleRight, Tornado, Torus, Touchpad, TouchpadOff, TowerControl, ToyBrick, Tractor,
  TrafficCone, Train, TrainFront, TrainFrontTunnel, TrainTrack, TramFront, Trash as TrashIcon, Trash2,
  TreeDeciduous, TreePalm, TreePine, Trees, Trello, TrendingDown, TrendingUp as TrendingUpIcon, Triangle,
  TriangleAlert, TriangleRight, Trophy as TrophyIcon, Truck as TruckIcon, Turtle, Tv as TvIcon, Tv2, TvMinimal,
  TvMinimalPlay, Twitch, Twitter, Type, TypeOutline, Umbrella as UmbrellaIcon, UmbrellaOff, Underline,
  Undo, Undo2, UnfoldHorizontal, UnfoldVertical, Ungroup, University, Unlink, Unlink2, Unplug,
  Upload as UploadIcon, UploadCloud, Usb, User as UserIcon, User2, UserCheck, UserCheck2, UserCircle,
  UserCircle2, UserCog, UserCog2, UserMinus, UserMinus2, UserPen, UserPlus, UserPlus2, UserRound,
  UserRoundCheck, UserRoundCog, UserRoundMinus, UserRoundPen, UserRoundPlus, UserRoundSearch,
  UserRoundX, UserSearch, UserX, UserX2, Users as UsersIcon, Users2, UsersRound, Utensils, UtensilsCrossed,
  UtilityPole, Variable, Vault, Vegan, VenetianMask, Vibrate, VibrateOff, Video as VideoIcon, VideoOff,
  Videotape, View, Voicemail as VoicemailIcon, Volleyball, Volume, Volume1, Volume2 as Volume2Icon, VolumeOff, VolumeX,
  Vote, Wallet as WalletIcon, Wallet2, WalletCards, WalletMinimal, Wallpaper, Wand, Wand2, WandSparkles,
  Warehouse, WashingMachine, Watch as WatchIcon, Waves, Waypoints, Webcam, Webhook, Weight, Wheat,
  WheatOff, WholeWord, Wifi as WifiIcon, WifiHigh, WifiLow, WifiOff, WifiZero, Wind as WindIcon, Wine, WineOff,
  Workflow, Worm, WrapText, Wrench as WrenchIcon, X as XIcon, XCircle, XOctagon, XSquare, Youtube as YoutubeIcon,
  Zap as ZapIcon, ZapOff, ZoomIn, ZoomOut
} from 'lucide-react';

interface IconSelectorProps {
  value: string;
  onChange: (value: string) => void;
  label?: string;
}

const IconSelector = ({ value, onChange, label = "Ícone" }: IconSelectorProps) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  
  const availableIcons = useMemo(() => [
    { name: 'Package', component: Package },
    { name: 'Search', component: Search },
    { name: 'User', component: User },
    { name: 'Building', component: Building },
    { name: 'Car', component: Car },
    { name: 'FileText', component: FileText },
    { name: 'Shield', component: Shield },
    { name: 'TrendingUp', component: TrendingUp },
    { name: 'Camera', component: Camera },
    { name: 'Phone', component: Phone },
    { name: 'Mail', component: Mail },
    { name: 'MapPin', component: MapPin },
    { name: 'Heart', component: Heart },
    { name: 'Star', component: Star },
    { name: 'Calendar', component: Calendar },
    { name: 'Clock', component: Clock },
    { name: 'Settings', component: Settings },
    { name: 'Database', component: Database },
    { name: 'Cloud', component: Cloud },
    { name: 'Lock', component: Lock },
    { name: 'Key', component: Key },
    { name: 'Eye', component: Eye },
    { name: 'Download', component: Download },
    { name: 'Upload', component: Upload },
    { name: 'BarChart', component: BarChart },
    { name: 'PieChart', component: PieChart },
    { name: 'LineChart', component: LineChart },
    { name: 'Edit', component: Edit },
    { name: 'Trash', component: Trash },
    { name: 'Plus', component: Plus },
    { name: 'Check', component: Check },
    { name: 'X', component: X },
    { name: 'Home', component: Home },
    { name: 'Globe', component: Globe },
    { name: 'Zap', component: Zap },
    { name: 'Target', component: Target },
    { name: 'Award', component: Award },
    { name: 'Gift', component: Gift },
    { name: 'Flag', component: Flag },
    { name: 'Bell', component: Bell },
    { name: 'MessageCircle', component: MessageCircle },
    { name: 'Activity', component: Activity },
    { name: 'Briefcase', component: Briefcase },
    { name: 'Calculator', component: Calculator },
    { name: 'CreditCard', component: CreditCard },
    { name: 'DollarSign', component: DollarSign },
    { name: 'Fingerprint', component: Fingerprint },
    { name: 'Folder', component: Folder },
    { name: 'HardDrive', component: HardDrive },
    { name: 'Headphones', component: Headphones },
    { name: 'Image', component: Image },
    { name: 'Laptop', component: Laptop },
    { name: 'Layers', component: Layers },
    { name: 'Link', component: Link },
    { name: 'Map', component: Map },
    { name: 'Percent', component: Percent },
    { name: 'Printer', component: Printer },
    { name: 'Smartphone', component: Smartphone },
    { name: 'Wrench', component: Wrench },
    { name: 'Truck', component: Truck },
    { name: 'Wallet', component: Wallet },
    { name: 'Wifi', component: Wifi },
    { name: 'Users', component: Users },
    { name: 'History', component: History },
    { name: 'AlertCircle', component: AlertCircle },
    { name: 'Anchor', component: Anchor },
    { name: 'Archive', component: Archive },
    { name: 'ArrowUpRight', component: ArrowUpRight },
    { name: 'Atom', component: Atom },
    { name: 'BadgeCheck', component: BadgeCheck },
    { name: 'Banknote', component: Banknote },
    { name: 'Battery', component: Battery },
    { name: 'Bluetooth', component: Bluetooth },
    { name: 'Bookmark', component: Bookmark },
    { name: 'Box', component: Box },
    { name: 'Brain', component: Brain },
    { name: 'Bug', component: Bug },
    { name: 'Cake', component: Cake },
    { name: 'CircleDollarSign', component: CircleDollarSign },
    { name: 'Clipboard', component: Clipboard },
    { name: 'Code', component: Code },
    { name: 'Compass', component: Compass },
    { name: 'Cpu', component: Cpu },
    { name: 'Crown', component: Crown },
    { name: 'Diamond', component: Diamond },
    { name: 'Disc', component: Disc },
    { name: 'Drama', component: Drama },
    { name: 'Dribbble', component: Dribbble },
    { name: 'Drum', component: Drum },
    { name: 'Eraser', component: Eraser },
    { name: 'Facebook', component: Facebook },
    { name: 'Feather', component: Feather },
    { name: 'Film', component: Film },
    { name: 'Filter', component: Filter },
    { name: 'Flame', component: Flame },
    { name: 'FlaskConical', component: FlaskConical },
    { name: 'Gamepad2', component: Gamepad2 },
    { name: 'Gauge', component: Gauge },
    { name: 'Gem', component: Gem },
    { name: 'Github', component: Github },
    { name: 'Glasses', component: Glasses },
    { name: 'GraduationCap', component: GraduationCap },
    { name: 'Hammer', component: Hammer },
    { name: 'Hash', component: Hash },
    { name: 'Hexagon', component: Hexagon },
    { name: 'Instagram', component: Instagram },
    { name: 'Joystick', component: Joystick },
    { name: 'Keyboard', component: Keyboard },
    { name: 'Landmark', component: Landmark },
    { name: 'LayoutGrid', component: LayoutGrid },
    { name: 'Lightbulb', component: Lightbulb },
    { name: 'Linkedin', component: Linkedin },
    { name: 'Magnet', component: Magnet },
    { name: 'Megaphone', component: Megaphone },
    { name: 'Microscope', component: Microscope },
    { name: 'Monitor', component: Monitor },
    { name: 'Moon', component: Moon },
    { name: 'Mountain', component: Mountain },
    { name: 'Music', component: Music },
    { name: 'Network', component: Network },
    { name: 'Newspaper', component: Newspaper },
    { name: 'Paintbrush', component: Paintbrush },
    { name: 'Palette', component: Palette },
    { name: 'Paperclip', component: Paperclip },
    { name: 'PenTool', component: PenTool },
    { name: 'Pizza', component: Pizza },
    { name: 'Plane', component: Plane },
    { name: 'Plug', component: Plug },
    { name: 'Podcast', component: Podcast },
    { name: 'Puzzle', component: Puzzle },
    { name: 'QrCode', component: QrCode },
    { name: 'Radio', component: Radio },
    { name: 'Rocket', component: Rocket },
    { name: 'Ruler', component: Ruler },
    { name: 'Scale', component: Scale },
    { name: 'Scissors', component: Scissors },
    { name: 'Server', component: Server },
    { name: 'Share2', component: Share2 },
    { name: 'ShieldCheck', component: ShieldCheck },
    { name: 'ShoppingBag', component: ShoppingBag },
    { name: 'ShoppingCart', component: ShoppingCart },
    { name: 'Signpost', component: Signpost },
    { name: 'Slack', component: Slack },
    { name: 'Smile', component: Smile },
    { name: 'Sparkles', component: Sparkles },
    { name: 'Speaker', component: Speaker },
    { name: 'Stethoscope', component: Stethoscope },
    { name: 'Sun', component: Sun },
    { name: 'Sword', component: Sword },
    { name: 'Tag', component: Tag },
    { name: 'Telescope', component: Telescope },
    { name: 'Terminal', component: Terminal },
    { name: 'ThumbsUp', component: ThumbsUp },
    { name: 'Timer', component: Timer },
    { name: 'ToggleLeft', component: ToggleLeft },
    { name: 'Trophy', component: Trophy },
    { name: 'Tv', component: Tv },
    { name: 'Umbrella', component: Umbrella },
    { name: 'Video', component: Video },
    { name: 'Voicemail', component: Voicemail },
    { name: 'Volume2', component: Volume2 },
    { name: 'Watch', component: Watch },
    { name: 'Wind', component: Wind },
    { name: 'Youtube', component: Youtube },
    // Novos ícones adicionados (500+)
    { name: 'Accessibility', component: Accessibility },
    { name: 'AirVent', component: AirVent },
    { name: 'Airplay', component: Airplay },
    { name: 'AlarmCheck', component: AlarmCheck },
    { name: 'AlarmClock', component: AlarmClock },
    { name: 'AlarmMinus', component: AlarmMinus },
    { name: 'AlarmPlus', component: AlarmPlus },
    { name: 'Album', component: Album },
    { name: 'AlertOctagon', component: AlertOctagon },
    { name: 'AlertTriangle', component: AlertTriangle },
    { name: 'AlignCenter', component: AlignCenter },
    { name: 'AlignJustify', component: AlignJustify },
    { name: 'AlignLeft', component: AlignLeft },
    { name: 'AlignRight', component: AlignRight },
    { name: 'Ampersand', component: Ampersand },
    { name: 'Angry', component: Angry },
    { name: 'Annoyed', component: Annoyed },
    { name: 'Antenna', component: Antenna },
    { name: 'Aperture', component: Aperture },
    { name: 'Apple', component: Apple },
    { name: 'ArchiveRestore', component: ArchiveRestore },
    { name: 'ArchiveX', component: ArchiveX },
    { name: 'Armchair', component: Armchair },
    { name: 'ArrowBigDown', component: ArrowBigDown },
    { name: 'ArrowBigLeft', component: ArrowBigLeft },
    { name: 'ArrowBigRight', component: ArrowBigRight },
    { name: 'ArrowBigUp', component: ArrowBigUp },
    { name: 'ArrowDown', component: ArrowDown },
    { name: 'ArrowDownCircle', component: ArrowDownCircle },
    { name: 'ArrowDownLeft', component: ArrowDownLeft },
    { name: 'ArrowDownRight', component: ArrowDownRight },
    { name: 'ArrowDownToLine', component: ArrowDownToLine },
    { name: 'ArrowLeft', component: ArrowLeft },
    { name: 'ArrowLeftCircle', component: ArrowLeftCircle },
    { name: 'ArrowLeftRight', component: ArrowLeftRight },
    { name: 'ArrowLeftToLine', component: ArrowLeftToLine },
    { name: 'ArrowRight', component: ArrowRight },
    { name: 'ArrowRightCircle', component: ArrowRightCircle },
    { name: 'ArrowRightLeft', component: ArrowRightLeft },
    { name: 'ArrowRightToLine', component: ArrowRightToLine },
    { name: 'ArrowUp', component: ArrowUp },
    { name: 'ArrowUpCircle', component: ArrowUpCircle },
    { name: 'ArrowUpDown', component: ArrowUpDown },
    { name: 'ArrowUpLeft', component: ArrowUpLeft },
    { name: 'ArrowUpToLine', component: ArrowUpToLine },
    { name: 'ArrowsUpFromLine', component: ArrowsUpFromLine },
    { name: 'Asterisk', component: Asterisk },
    { name: 'AtSign', component: AtSign },
    { name: 'AudioLines', component: AudioLines },
    { name: 'AudioWaveform', component: AudioWaveform },
    { name: 'Axe', component: Axe },
    { name: 'Baby', component: Baby },
    { name: 'Backpack', component: Backpack },
    { name: 'BadgeAlert', component: BadgeAlert },
    { name: 'BadgeCent', component: BadgeCent },
    { name: 'BadgeDollarSign', component: BadgeDollarSign },
    { name: 'BadgeEuro', component: BadgeEuro },
    { name: 'BadgeHelp', component: BadgeHelp },
    { name: 'BadgeIndianRupee', component: BadgeIndianRupee },
    { name: 'BadgeInfo', component: BadgeInfo },
    { name: 'BadgeJapaneseYen', component: BadgeJapaneseYen },
    { name: 'BadgeMinus', component: BadgeMinus },
    { name: 'BadgePercent', component: BadgePercent },
    { name: 'BadgePlus', component: BadgePlus },
    { name: 'BadgePoundSterling', component: BadgePoundSterling },
    { name: 'BadgeRussianRuble', component: BadgeRussianRuble },
    { name: 'BadgeSwissFranc', component: BadgeSwissFranc },
    { name: 'BadgeX', component: BadgeX },
    { name: 'BaggageClaim', component: BaggageClaim },
    { name: 'Banana', component: Banana },
    { name: 'Bandage', component: Bandage },
    { name: 'Barcode', component: Barcode },
    { name: 'Baseline', component: Baseline },
    { name: 'Bath', component: Bath },
    { name: 'BatteryCharging', component: BatteryCharging },
    { name: 'BatteryFull', component: BatteryFull },
    { name: 'BatteryLow', component: BatteryLow },
    { name: 'BatteryMedium', component: BatteryMedium },
    { name: 'BatteryWarning', component: BatteryWarning },
    { name: 'Beaker', component: Beaker },
    { name: 'Bean', component: Bean },
    { name: 'BeanOff', component: BeanOff },
    { name: 'Bed', component: Bed },
    { name: 'BedDouble', component: BedDouble },
    { name: 'BedSingle', component: BedSingle },
    { name: 'Beef', component: Beef },
    { name: 'Beer', component: Beer },
    { name: 'BellDot', component: BellDot },
    { name: 'BellMinus', component: BellMinus },
    { name: 'BellOff', component: BellOff },
    { name: 'BellPlus', component: BellPlus },
    { name: 'BellRing', component: BellRing },
    { name: 'BetweenHorizontalEnd', component: BetweenHorizontalEnd },
    { name: 'BetweenHorizontalStart', component: BetweenHorizontalStart },
    { name: 'BetweenVerticalEnd', component: BetweenVerticalEnd },
    { name: 'BetweenVerticalStart', component: BetweenVerticalStart },
    { name: 'Bike', component: Bike },
    { name: 'Binary', component: Binary },
    { name: 'Binoculars', component: Binoculars },
    { name: 'Biohazard', component: Biohazard },
    { name: 'Bird', component: Bird },
    { name: 'Bitcoin', component: Bitcoin },
    { name: 'Blend', component: Blend },
    { name: 'Blinds', component: Blinds },
    { name: 'Blocks', component: Blocks },
    { name: 'BluetoothConnected', component: BluetoothConnected },
    { name: 'BluetoothOff', component: BluetoothOff },
    { name: 'BluetoothSearching', component: BluetoothSearching },
    { name: 'Bold', component: Bold },
    { name: 'Bomb', component: Bomb },
    { name: 'Bone', component: Bone },
    { name: 'Book', component: Book },
    { name: 'BookA', component: BookA },
    { name: 'BookAudio', component: BookAudio },
    { name: 'BookCheck', component: BookCheck },
    { name: 'BookCopy', component: BookCopy },
    { name: 'BookDashed', component: BookDashed },
    { name: 'BookDown', component: BookDown },
    { name: 'BookHeadphones', component: BookHeadphones },
    { name: 'BookHeart', component: BookHeart },
    { name: 'BookImage', component: BookImage },
    { name: 'BookKey', component: BookKey },
    { name: 'BookLock', component: BookLock },
    { name: 'BookMarked', component: BookMarked },
    { name: 'BookMinus', component: BookMinus },
    { name: 'BookOpen', component: BookOpen },
    { name: 'BookOpenCheck', component: BookOpenCheck },
    { name: 'BookOpenText', component: BookOpenText },
    { name: 'BookPlus', component: BookPlus },
    { name: 'BookText', component: BookText },
    { name: 'BookType', component: BookType },
    { name: 'BookUp', component: BookUp },
    { name: 'BookUser', component: BookUser },
    { name: 'BookX', component: BookX },
    { name: 'Bot', component: Bot },
    { name: 'BotMessageSquare', component: BotMessageSquare },
    { name: 'Boxes', component: Boxes },
    { name: 'Braces', component: Braces },
    { name: 'BrainCircuit', component: BrainCircuit },
    { name: 'BrainCog', component: BrainCog },
    { name: 'BrickWall', component: BrickWall },
    { name: 'BringToFront', component: BringToFront },
    { name: 'Brush', component: Brush },
    { name: 'BugOff', component: BugOff },
    { name: 'BugPlay', component: BugPlay },
    { name: 'Building2', component: Building2 },
    { name: 'BusFront', component: BusFront },
    { name: 'Cable', component: Cable },
    { name: 'CableCar', component: CableCar },
    { name: 'CakeSlice', component: CakeSlice },
    { name: 'CalendarCheck', component: CalendarCheck },
    { name: 'CalendarCheck2', component: CalendarCheck2 },
    { name: 'CalendarClock', component: CalendarClock },
    { name: 'CalendarDays', component: CalendarDays },
    { name: 'CalendarHeart', component: CalendarHeart },
    { name: 'CalendarMinus', component: CalendarMinus },
    { name: 'CalendarOff', component: CalendarOff },
    { name: 'CalendarPlus', component: CalendarPlus },
    { name: 'CalendarRange', component: CalendarRange },
    { name: 'CalendarSearch', component: CalendarSearch },
    { name: 'CalendarX', component: CalendarX },
    { name: 'CalendarX2', component: CalendarX2 },
    { name: 'CameraOff', component: CameraOff },
    { name: 'Candy', component: Candy },
    { name: 'CandyCane', component: CandyCane },
    { name: 'CandyOff', component: CandyOff },
    { name: 'Cannabis', component: Cannabis },
    { name: 'Captions', component: Captions },
    { name: 'CaptionsOff', component: CaptionsOff },
    { name: 'CarFront', component: CarFront },
    { name: 'CarTaxiFront', component: CarTaxiFront },
    { name: 'Caravan', component: Caravan },
    { name: 'Carrot', component: Carrot },
    { name: 'CaseLower', component: CaseLower },
    { name: 'CaseSensitive', component: CaseSensitive },
    { name: 'CaseUpper', component: CaseUpper },
    { name: 'Cast', component: Cast },
    { name: 'Castle', component: Castle },
    { name: 'Cat', component: Cat },
    { name: 'ChartArea', component: ChartArea },
    { name: 'ChartBar', component: ChartBar },
    { name: 'ChartBarBig', component: ChartBarBig },
    { name: 'ChartBarDecreasing', component: ChartBarDecreasing },
    { name: 'ChartBarIncreasing', component: ChartBarIncreasing },
    { name: 'ChartBarStacked', component: ChartBarStacked },
    { name: 'ChartCandlestick', component: ChartCandlestick },
    { name: 'ChartColumn', component: ChartColumn },
    { name: 'ChartColumnBig', component: ChartColumnBig },
    { name: 'ChartColumnDecreasing', component: ChartColumnDecreasing },
    { name: 'ChartColumnIncreasing', component: ChartColumnIncreasing },
    { name: 'ChartColumnStacked', component: ChartColumnStacked },
    { name: 'ChartGantt', component: ChartGantt },
    { name: 'ChartLine', component: ChartLine },
    { name: 'ChartNetwork', component: ChartNetwork },
    { name: 'ChartNoAxesColumn', component: ChartNoAxesColumn },
    { name: 'ChartNoAxesCombined', component: ChartNoAxesCombined },
    { name: 'ChartNoAxesGantt', component: ChartNoAxesGantt },
    { name: 'ChartPie', component: ChartPie },
    { name: 'ChartScatter', component: ChartScatter },
    { name: 'ChartSpline', component: ChartSpline },
    { name: 'CheckCheck', component: CheckCheck },
    { name: 'CheckCircle', component: CheckCircle },
    { name: 'CheckCircle2', component: CheckCircle2 },
    { name: 'CheckSquare', component: CheckSquare },
    { name: 'ChefHat', component: ChefHat },
    { name: 'Cherry', component: Cherry },
    { name: 'ChevronDown', component: ChevronDown },
    { name: 'ChevronFirst', component: ChevronFirst },
    { name: 'ChevronLast', component: ChevronLast },
    { name: 'ChevronLeft', component: ChevronLeft },
    { name: 'ChevronRight', component: ChevronRight },
    { name: 'ChevronUp', component: ChevronUp },
    { name: 'ChevronsDown', component: ChevronsDown },
    { name: 'ChevronsDownUp', component: ChevronsDownUp },
    { name: 'ChevronsLeft', component: ChevronsLeft },
    { name: 'ChevronsLeftRight', component: ChevronsLeftRight },
    { name: 'ChevronsRight', component: ChevronsRight },
    { name: 'ChevronsRightLeft', component: ChevronsRightLeft },
    { name: 'ChevronsUp', component: ChevronsUp },
    { name: 'ChevronsUpDown', component: ChevronsUpDown },
    { name: 'Chrome', component: Chrome },
    { name: 'Church', component: Church },
    { name: 'Cigarette', component: Cigarette },
    { name: 'CigaretteOff', component: CigaretteOff },
    { name: 'Circle', component: Circle },
    { name: 'CircleAlert', component: CircleAlert },
    { name: 'CircleArrowDown', component: CircleArrowDown },
    { name: 'CircleArrowLeft', component: CircleArrowLeft },
    { name: 'CircleArrowOutDownLeft', component: CircleArrowOutDownLeft },
    { name: 'CircleArrowOutDownRight', component: CircleArrowOutDownRight },
    { name: 'CircleArrowOutUpLeft', component: CircleArrowOutUpLeft },
    { name: 'CircleArrowOutUpRight', component: CircleArrowOutUpRight },
    { name: 'CircleArrowRight', component: CircleArrowRight },
    { name: 'CircleArrowUp', component: CircleArrowUp },
    { name: 'CircleCheck', component: CircleCheck },
    { name: 'CircleCheckBig', component: CircleCheckBig },
    { name: 'CircleDashed', component: CircleDashed },
    { name: 'CircleDivide', component: CircleDivide },
    { name: 'CircleDot', component: CircleDot },
    { name: 'CircleDotDashed', component: CircleDotDashed },
    { name: 'CircleEllipsis', component: CircleEllipsis },
    { name: 'CircleEqual', component: CircleEqual },
    { name: 'CircleFadingPlus', component: CircleFadingPlus },
    { name: 'CircleGauge', component: CircleGauge },
    { name: 'CircleHelp', component: CircleHelp },
    { name: 'CircleMinus', component: CircleMinus },
    { name: 'CircleOff', component: CircleOff },
    { name: 'CircleParking', component: CircleParking },
    { name: 'CircleParkingOff', component: CircleParkingOff },
    { name: 'CirclePause', component: CirclePause },
    { name: 'CirclePercent', component: CirclePercent },
    { name: 'CirclePlay', component: CirclePlay },
    { name: 'CirclePlus', component: CirclePlus },
    { name: 'CirclePower', component: CirclePower },
    { name: 'CircleSlash', component: CircleSlash },
    { name: 'CircleSlash2', component: CircleSlash2 },
    { name: 'CircleStop', component: CircleStop },
    { name: 'CircleUser', component: CircleUser },
    { name: 'CircleUserRound', component: CircleUserRound },
    { name: 'CircleX', component: CircleX },
    { name: 'CircuitBoard', component: CircuitBoard },
    { name: 'Citrus', component: Citrus },
    { name: 'Clapperboard', component: Clapperboard },
    { name: 'ClipboardCheck', component: ClipboardCheck },
    { name: 'ClipboardCopy', component: ClipboardCopy },
    { name: 'ClipboardList', component: ClipboardList },
    { name: 'ClipboardMinus', component: ClipboardMinus },
    { name: 'ClipboardPaste', component: ClipboardPaste },
    { name: 'ClipboardPen', component: ClipboardPen },
    { name: 'ClipboardPlus', component: ClipboardPlus },
    { name: 'ClipboardType', component: ClipboardType },
    { name: 'ClipboardX', component: ClipboardX },
    { name: 'ClockAlert', component: ClockAlert },
    { name: 'Clock1', component: Clock1 },
    { name: 'Clock10', component: Clock10 },
    { name: 'Clock11', component: Clock11 },
    { name: 'Clock12', component: Clock12 },
    { name: 'Clock2', component: Clock2 },
    { name: 'Clock3', component: Clock3 },
    { name: 'Clock4', component: Clock4 },
    { name: 'Clock5', component: Clock5 },
    { name: 'Clock6', component: Clock6 },
    { name: 'Clock7', component: Clock7 },
    { name: 'Clock8', component: Clock8 },
    { name: 'Clock9', component: Clock9 },
    { name: 'CloudCog', component: CloudCog },
    { name: 'CloudDownload', component: CloudDownload },
    { name: 'CloudDrizzle', component: CloudDrizzle },
    { name: 'CloudFog', component: CloudFog },
    { name: 'CloudHail', component: CloudHail },
    { name: 'CloudLightning', component: CloudLightning },
    { name: 'CloudMoon', component: CloudMoon },
    { name: 'CloudMoonRain', component: CloudMoonRain },
    { name: 'CloudOff', component: CloudOff },
    { name: 'CloudRain', component: CloudRain },
    { name: 'CloudRainWind', component: CloudRainWind },
    { name: 'CloudSnow', component: CloudSnow },
    { name: 'CloudSun', component: CloudSun },
    { name: 'CloudSunRain', component: CloudSunRain },
    { name: 'CloudUpload', component: CloudUpload },
    { name: 'Cloudy', component: Cloudy },
    { name: 'Clover', component: Clover },
    { name: 'Club', component: Club },
    { name: 'CodeSquare', component: CodeSquare },
    { name: 'CodeXml', component: CodeXml },
    { name: 'Codepen', component: Codepen },
    { name: 'Codesandbox', component: Codesandbox },
    { name: 'Coffee', component: Coffee },
    { name: 'Cog', component: Cog },
    { name: 'Coins', component: Coins },
    { name: 'Columns2', component: Columns2 },
    { name: 'Columns3', component: Columns3 },
    { name: 'Columns4', component: Columns4 },
    { name: 'Combine', component: Combine },
    { name: 'Command', component: Command },
    { name: 'Command', component: Command },
    { name: 'Component', component: Component },
    { name: 'Computer', component: Computer },
    { name: 'ConciergeBell', component: ConciergeBell },
    { name: 'Cone', component: Cone },
    { name: 'Construction', component: Construction },
    { name: 'Contact', component: Contact },
    { name: 'ContactRound', component: ContactRound },
    { name: 'Container', component: Container },
    { name: 'Contrast', component: Contrast },
    { name: 'Cookie', component: Cookie },
    { name: 'CookingPot', component: CookingPot },
    { name: 'Copy', component: Copy },
    { name: 'CopyCheck', component: CopyCheck },
    { name: 'CopyMinus', component: CopyMinus },
    { name: 'CopyPlus', component: CopyPlus },
    { name: 'CopySlash', component: CopySlash },
    { name: 'CopyX', component: CopyX },
    { name: 'Copyleft', component: Copyleft },
    { name: 'Copyright', component: Copyright },
    { name: 'CornerDownLeft', component: CornerDownLeft },
    { name: 'CornerDownRight', component: CornerDownRight },
    { name: 'CornerLeftDown', component: CornerLeftDown },
    { name: 'CornerLeftUp', component: CornerLeftUp },
    { name: 'CornerRightDown', component: CornerRightDown },
    { name: 'CornerRightUp', component: CornerRightUp },
    { name: 'CornerUpLeft', component: CornerUpLeft },
    { name: 'CornerUpRight', component: CornerUpRight },
    { name: 'Croissant', component: Croissant },
    { name: 'Crop', component: Crop },
    { name: 'Cross', component: Cross },
    { name: 'Crosshair', component: Crosshair },
    { name: 'CupSoda', component: CupSoda },
    { name: 'Currency', component: Currency },
    { name: 'Cylinder', component: Cylinder },
    { name: 'DatabaseBackup', component: DatabaseBackup },
    { name: 'DatabaseZap', component: DatabaseZap },
    { name: 'Delete', component: Delete },
    { name: 'Dessert', component: Dessert },
    { name: 'Diameter', component: Diameter },
    { name: 'DiamondMinus', component: DiamondMinus },
    { name: 'DiamondPercent', component: DiamondPercent },
    { name: 'DiamondPlus', component: DiamondPlus },
    { name: 'Dice1', component: Dice1 },
    { name: 'Dice2', component: Dice2 },
    { name: 'Dice3', component: Dice3 },
    { name: 'Dice4', component: Dice4 },
    { name: 'Dice5', component: Dice5 },
    { name: 'Dice6', component: Dice6 },
    { name: 'Dices', component: Dices },
    { name: 'Diff', component: Diff },
    { name: 'Disc2', component: Disc2 },
    { name: 'Disc3', component: Disc3 },
    { name: 'DiscAlbum', component: DiscAlbum },
    { name: 'Divide', component: Divide },
    { name: 'DnaOff', component: DnaOff },
    { name: 'Dna', component: Dna },
    { name: 'Dock', component: Dock },
    { name: 'Dog', component: Dog },
    { name: 'DoorClosed', component: DoorClosed },
    { name: 'DoorOpen', component: DoorOpen },
    { name: 'Dot', component: Dot },
    { name: 'DraftingCompass', component: DraftingCompass },
    { name: 'Droplet', component: Droplet },
    { name: 'Droplets', component: Droplets },
    { name: 'Drumstick', component: Drumstick },
    { name: 'Dumbbell', component: Dumbbell },
    { name: 'Ear', component: Ear },
    { name: 'EarOff', component: EarOff },
    { name: 'Eclipse', component: Eclipse },
    { name: 'EggFried', component: EggFried },
    { name: 'EggOff', component: EggOff },
    { name: 'Egg', component: Egg },
    { name: 'Ellipsis', component: Ellipsis },
    { name: 'EllipsisVertical', component: EllipsisVertical },
    { name: 'Equal', component: Equal },
    { name: 'EqualNot', component: EqualNot },
    { name: 'EqualSquare', component: EqualSquare },
    { name: 'Euro', component: Euro },
    { name: 'Expand', component: Expand },
    { name: 'ExternalLink', component: ExternalLink },
    { name: 'EyeOff', component: EyeOff },
    { name: 'Factory', component: Factory },
    { name: 'Fan', component: Fan },
    { name: 'FastForward', component: FastForward },
    { name: 'Fence', component: Fence },
    { name: 'FerrisWheel', component: FerrisWheel },
    { name: 'Figma', component: Figma },
    { name: 'File', component: File },
    { name: 'FileArchive', component: FileArchive },
    { name: 'FileAudio', component: FileAudio },
    { name: 'FileAudio2', component: FileAudio2 },
    { name: 'FileAxis3d', component: FileAxis3d },
    { name: 'FileBadge', component: FileBadge },
    { name: 'FileBadge2', component: FileBadge2 },
    { name: 'FileBarChart', component: FileBarChart },
    { name: 'FileBarChart2', component: FileBarChart2 },
    { name: 'FileBox', component: FileBox },
    { name: 'FileCheck', component: FileCheck },
    { name: 'FileCheck2', component: FileCheck2 },
    { name: 'FileClock', component: FileClock },
    { name: 'FileCode', component: FileCode },
    { name: 'FileCode2', component: FileCode2 },
    { name: 'FileCog', component: FileCog },
    { name: 'FileDiff', component: FileDiff },
    { name: 'FileDigit', component: FileDigit },
    { name: 'FileDown', component: FileDown },
    { name: 'FileHeart', component: FileHeart },
    { name: 'FileImage', component: FileImage },
    { name: 'FileInput', component: FileInput },
    { name: 'FileJson', component: FileJson },
    { name: 'FileJson2', component: FileJson2 },
    { name: 'FileKey', component: FileKey },
    { name: 'FileKey2', component: FileKey2 },
    { name: 'FileLineChart', component: FileLineChart },
    { name: 'FileLock', component: FileLock },
    { name: 'FileLock2', component: FileLock2 },
    { name: 'FileMinus', component: FileMinus },
    { name: 'FileMinus2', component: FileMinus2 },
    { name: 'FileMusic', component: FileMusic },
    { name: 'FileOutput', component: FileOutput },
    { name: 'FilePen', component: FilePen },
    { name: 'FilePenLine', component: FilePenLine },
    { name: 'FilePieChart', component: FilePieChart },
    { name: 'FilePlus', component: FilePlus },
    { name: 'FilePlus2', component: FilePlus2 },
    { name: 'FileQuestion', component: FileQuestion },
    { name: 'FileScan', component: FileScan },
    { name: 'FileSearch', component: FileSearch },
    { name: 'FileSearch2', component: FileSearch2 },
    { name: 'FileSignature', component: FileSignature },
    { name: 'FileSliders', component: FileSliders },
    { name: 'FileSpreadsheet', component: FileSpreadsheet },
    { name: 'FileStack', component: FileStack },
    { name: 'FileSymlink', component: FileSymlink },
    { name: 'FileTerminal', component: FileTerminal },
    { name: 'FileType', component: FileType },
    { name: 'FileType2', component: FileType2 },
    { name: 'FileUp', component: FileUp },
    { name: 'FileVideo', component: FileVideo },
    { name: 'FileVideo2', component: FileVideo2 },
    { name: 'FileVolume', component: FileVolume },
    { name: 'FileVolume2', component: FileVolume2 },
    { name: 'FileWarning', component: FileWarning },
    { name: 'FileX', component: FileX },
    { name: 'FileX2', component: FileX2 },
    { name: 'Files', component: Files },
    { name: 'FireExtinguisher', component: FireExtinguisher },
    { name: 'Fish', component: Fish },
    { name: 'FishOff', component: FishOff },
    { name: 'FishSymbol', component: FishSymbol },
    { name: 'FlagOff', component: FlagOff },
    { name: 'FlagTriangleLeft', component: FlagTriangleLeft },
    { name: 'FlagTriangleRight', component: FlagTriangleRight },
    { name: 'FlameKindling', component: FlameKindling },
    { name: 'Flashlight', component: Flashlight },
    { name: 'FlashlightOff', component: FlashlightOff },
    { name: 'FlaskRound', component: FlaskRound },
    { name: 'FlipHorizontal', component: FlipHorizontal },
    { name: 'FlipHorizontal2', component: FlipHorizontal2 },
    { name: 'FlipVertical', component: FlipVertical },
    { name: 'FlipVertical2', component: FlipVertical2 },
    { name: 'Flower', component: Flower },
    { name: 'Flower2', component: Flower2 },
    { name: 'Focus', component: Focus },
    { name: 'FoldHorizontal', component: FoldHorizontal },
    { name: 'FoldVertical', component: FoldVertical },
    { name: 'FolderArchive', component: FolderArchive },
    { name: 'FolderCheck', component: FolderCheck },
    { name: 'FolderClock', component: FolderClock },
    { name: 'FolderClosed', component: FolderClosed },
    { name: 'FolderCog', component: FolderCog },
    { name: 'FolderDot', component: FolderDot },
    { name: 'FolderDown', component: FolderDown },
    { name: 'FolderGit', component: FolderGit },
    { name: 'FolderGit2', component: FolderGit2 },
    { name: 'FolderHeart', component: FolderHeart },
    { name: 'FolderInput', component: FolderInput },
    { name: 'FolderKanban', component: FolderKanban },
    { name: 'FolderKey', component: FolderKey },
    { name: 'FolderLock', component: FolderLock },
    { name: 'FolderMinus', component: FolderMinus },
    { name: 'FolderOpen', component: FolderOpen },
    { name: 'FolderOpenDot', component: FolderOpenDot },
    { name: 'FolderOutput', component: FolderOutput },
    { name: 'FolderPen', component: FolderPen },
    { name: 'FolderPlus', component: FolderPlus },
    { name: 'FolderRoot', component: FolderRoot },
    { name: 'FolderSearch', component: FolderSearch },
    { name: 'FolderSearch2', component: FolderSearch2 },
    { name: 'FolderSymlink', component: FolderSymlink },
    { name: 'FolderSync', component: FolderSync },
    { name: 'FolderTree', component: FolderTree },
    { name: 'FolderUp', component: FolderUp },
    { name: 'FolderX', component: FolderX },
    { name: 'Folders', component: Folders },
    { name: 'Footprints', component: Footprints },
    { name: 'Forklift', component: Forklift },
    { name: 'Forward', component: Forward },
    { name: 'Frame', component: Frame },
    { name: 'Framer', component: Framer },
    { name: 'Frown', component: Frown },
    { name: 'Fuel', component: Fuel },
    { name: 'Fullscreen', component: Fullscreen },
    { name: 'GalleryHorizontal', component: GalleryHorizontal },
    { name: 'GalleryHorizontalEnd', component: GalleryHorizontalEnd },
    { name: 'GalleryThumbnails', component: GalleryThumbnails },
    { name: 'GalleryVertical', component: GalleryVertical },
    { name: 'GalleryVerticalEnd', component: GalleryVerticalEnd },
    { name: 'Gamepad', component: Gamepad },
    { name: 'Gavel', component: Gavel },
    { name: 'Ghost', component: Ghost },
    { name: 'GitBranch', component: GitBranch },
    { name: 'GitBranchPlus', component: GitBranchPlus },
    { name: 'GitCommitHorizontal', component: GitCommitHorizontal },
    { name: 'GitCommitVertical', component: GitCommitVertical },
    { name: 'GitCompare', component: GitCompare },
    { name: 'GitCompareArrows', component: GitCompareArrows },
    { name: 'GitFork', component: GitFork },
    { name: 'GitGraph', component: GitGraph },
    { name: 'GitMerge', component: GitMerge },
    { name: 'GitPullRequest', component: GitPullRequest },
    { name: 'GitPullRequestArrow', component: GitPullRequestArrow },
    { name: 'GitPullRequestClosed', component: GitPullRequestClosed },
    { name: 'GitPullRequestCreate', component: GitPullRequestCreate },
    { name: 'GitPullRequestDraft', component: GitPullRequestDraft },
    { name: 'Gitlab', component: Gitlab },
    { name: 'GlassWater', component: GlassWater },
    { name: 'Globe2', component: Globe2 },
    { name: 'GlobeLock', component: GlobeLock },
    { name: 'Goal', component: Goal },
    { name: 'Grab', component: Grab },
    { name: 'Grape', component: Grape },
    { name: 'Grid2x2', component: Grid2x2 },
    { name: 'Grid2x2Check', component: Grid2x2Check },
    { name: 'Grid2x2Plus', component: Grid2x2Plus },
    { name: 'Grid2x2X', component: Grid2x2X },
    { name: 'Grid3x3', component: Grid3x3 },
    { name: 'Grip', component: Grip },
    { name: 'GripHorizontal', component: GripHorizontal },
    { name: 'GripVertical', component: GripVertical },
    { name: 'Group', component: Group },
    { name: 'Guitar', component: Guitar },
    { name: 'Ham', component: Ham },
    { name: 'Hand', component: Hand },
    { name: 'HandCoins', component: HandCoins },
    { name: 'HandHeart', component: HandHeart },
    { name: 'HandHelping', component: HandHelping },
    { name: 'HandMetal', component: HandMetal },
    { name: 'HandPlatter', component: HandPlatter },
    { name: 'Handshake', component: Handshake },
    { name: 'HardDriveDownload', component: HardDriveDownload },
    { name: 'HardDriveUpload', component: HardDriveUpload },
    { name: 'HardHat', component: HardHat },
    { name: 'Haze', component: Haze },
    { name: 'HdmiPort', component: HdmiPort },
    { name: 'Heading', component: Heading },
    { name: 'Heading1', component: Heading1 },
    { name: 'Heading2', component: Heading2 },
    { name: 'Heading3', component: Heading3 },
    { name: 'Heading4', component: Heading4 },
    { name: 'Heading5', component: Heading5 },
    { name: 'Heading6', component: Heading6 },
    { name: 'HeadphoneOff', component: HeadphoneOff },
    { name: 'Headset', component: Headset },
    { name: 'HeartCrack', component: HeartCrack },
    { name: 'HeartHandshake', component: HeartHandshake },
    { name: 'HeartOff', component: HeartOff },
    { name: 'HeartPulse', component: HeartPulse },
    { name: 'Heater', component: Heater },
    { name: 'Highlighter', component: Highlighter },
    { name: 'Hop', component: Hop },
    { name: 'HopOff', component: HopOff },
    { name: 'Hospital', component: Hospital },
    { name: 'Hotel', component: Hotel },
    { name: 'Hourglass', component: Hourglass },
    { name: 'House', component: House },
    { name: 'HousePlug', component: HousePlug },
    { name: 'HousePlus', component: HousePlus },
    { name: 'IceCream', component: IceCream },
    { name: 'IceCreamBowl', component: IceCreamBowl },
    { name: 'IceCreamCone', component: IceCreamCone },
    { name: 'IdCard', component: IdCard },
    { name: 'ImageDown', component: ImageDown },
    { name: 'ImageMinus', component: ImageMinus },
    { name: 'ImageOff', component: ImageOff },
    { name: 'ImagePlay', component: ImagePlay },
    { name: 'ImagePlus', component: ImagePlus },
    { name: 'ImageUp', component: ImageUp },
    { name: 'Images', component: Images },
    { name: 'Import', component: Import },
    { name: 'Inbox', component: Inbox },
    { name: 'Indent', component: Indent },
    { name: 'IndentDecrease', component: IndentDecrease },
    { name: 'IndentIncrease', component: IndentIncrease },
    { name: 'IndianRupee', component: IndianRupee },
    { name: 'Infinity', component: Infinity },
    { name: 'Info', component: Info },
    { name: 'InspectionPanel', component: InspectionPanel },
    { name: 'Italic', component: Italic },
    { name: 'IterationCcw', component: IterationCcw },
    { name: 'IterationCw', component: IterationCw },
    { name: 'JapaneseYen', component: JapaneseYen },
    { name: 'Kanban', component: Kanban },
    { name: 'KeyRound', component: KeyRound },
    { name: 'KeySquare', component: KeySquare },
    { name: 'KeyboardMusic', component: KeyboardMusic },
    { name: 'KeyboardOff', component: KeyboardOff },
    { name: 'Lamp', component: Lamp },
    { name: 'LampCeiling', component: LampCeiling },
    { name: 'LampDesk', component: LampDesk },
    { name: 'LampFloor', component: LampFloor },
    { name: 'LampWallDown', component: LampWallDown },
    { name: 'LampWallUp', component: LampWallUp },
    { name: 'LandPlot', component: LandPlot },
    { name: 'Languages', component: Languages },
    { name: 'Laptop2', component: Laptop2 },
    { name: 'LaptopMinimal', component: LaptopMinimal },
    { name: 'Lasso', component: Lasso },
    { name: 'LassoSelect', component: LassoSelect },
    { name: 'Laugh', component: Laugh },
    { name: 'Layers2', component: Layers2 },
    { name: 'Layers3', component: Layers3 },
    { name: 'LayoutDashboard', component: LayoutDashboard },
    { name: 'LayoutList', component: LayoutList },
    { name: 'LayoutPanelLeft', component: LayoutPanelLeft },
    { name: 'LayoutPanelTop', component: LayoutPanelTop },
    { name: 'LayoutTemplate', component: LayoutTemplate },
    { name: 'Leaf', component: Leaf },
    { name: 'LeafyGreen', component: LeafyGreen },
    { name: 'Lectern', component: Lectern },
    { name: 'LetterText', component: LetterText },
    { name: 'Library', component: Library },
    { name: 'LibraryBig', component: LibraryBig },
    { name: 'LifeBuoy', component: LifeBuoy },
    { name: 'Ligature', component: Ligature },
    { name: 'LightbulbOff', component: LightbulbOff },
    { name: 'Link2', component: Link2 },
    { name: 'Link2Off', component: Link2Off },
    { name: 'List', component: List },
    { name: 'ListCheck', component: ListCheck },
    { name: 'ListChecks', component: ListChecks },
    { name: 'ListCollapse', component: ListCollapse },
    { name: 'ListEnd', component: ListEnd },
    { name: 'ListFilter', component: ListFilter },
    { name: 'ListMinus', component: ListMinus },
    { name: 'ListMusic', component: ListMusic },
    { name: 'ListOrdered', component: ListOrdered },
    { name: 'ListPlus', component: ListPlus },
    { name: 'ListRestart', component: ListRestart },
    { name: 'ListStart', component: ListStart },
    { name: 'ListTodo', component: ListTodo },
    { name: 'ListTree', component: ListTree },
    { name: 'ListVideo', component: ListVideo },
    { name: 'ListX', component: ListX },
    { name: 'Loader', component: Loader },
    { name: 'Loader2', component: Loader2 },
    { name: 'LoaderCircle', component: LoaderCircle },
    { name: 'LoaderPinwheel', component: LoaderPinwheel },
    { name: 'Locate', component: Locate },
    { name: 'LocateFixed', component: LocateFixed },
    { name: 'LocateOff', component: LocateOff },
    { name: 'LockKeyhole', component: LockKeyhole },
    { name: 'LockKeyholeOpen', component: LockKeyholeOpen },
    { name: 'LockOpen', component: LockOpen },
    { name: 'LogIn', component: LogIn },
    { name: 'LogOut', component: LogOut },
    { name: 'Logs', component: Logs },
    { name: 'Lollipop', component: Lollipop },
    { name: 'Luggage', component: Luggage },
    { name: 'MailCheck', component: MailCheck },
    { name: 'MailMinus', component: MailMinus },
    { name: 'MailOpen', component: MailOpen },
    { name: 'MailPlus', component: MailPlus },
    { name: 'MailQuestion', component: MailQuestion },
    { name: 'MailSearch', component: MailSearch },
    { name: 'MailWarning', component: MailWarning },
    { name: 'MailX', component: MailX },
    { name: 'Mailbox', component: Mailbox },
    { name: 'Mails', component: Mails },
    { name: 'MapPinCheck', component: MapPinCheck },
    { name: 'MapPinCheckInside', component: MapPinCheckInside },
    { name: 'MapPinHouse', component: MapPinHouse },
    { name: 'MapPinMinus', component: MapPinMinus },
    { name: 'MapPinMinusInside', component: MapPinMinusInside },
    { name: 'MapPinOff', component: MapPinOff },
    { name: 'MapPinPlus', component: MapPinPlus },
    { name: 'MapPinPlusInside', component: MapPinPlusInside },
    { name: 'MapPinX', component: MapPinX },
    { name: 'MapPinXInside', component: MapPinXInside },
    { name: 'MapPinned', component: MapPinned },
    { name: 'Martini', component: Martini },
    { name: 'Maximize', component: Maximize },
    { name: 'Maximize2', component: Maximize2 },
    { name: 'Medal', component: Medal },
    { name: 'Meh', component: Meh },
    { name: 'MemoryStick', component: MemoryStick },
    { name: 'Menu', component: Menu },
    { name: 'Merge', component: Merge },
    { name: 'MessageCircleCode', component: MessageCircleCode },
    { name: 'MessageCircleDashed', component: MessageCircleDashed },
    { name: 'MessageCircleHeart', component: MessageCircleHeart },
    { name: 'MessageCircleMore', component: MessageCircleMore },
    { name: 'MessageCircleOff', component: MessageCircleOff },
    { name: 'MessageCirclePlus', component: MessageCirclePlus },
    { name: 'MessageCircleQuestion', component: MessageCircleQuestion },
    { name: 'MessageCircleReply', component: MessageCircleReply },
    { name: 'MessageCircleWarning', component: MessageCircleWarning },
    { name: 'MessageCircleX', component: MessageCircleX },
    { name: 'MessageSquare', component: MessageSquare },
    { name: 'MessageSquareCode', component: MessageSquareCode },
    { name: 'MessageSquareDashed', component: MessageSquareDashed },
    { name: 'MessageSquareDiff', component: MessageSquareDiff },
    { name: 'MessageSquareDot', component: MessageSquareDot },
    { name: 'MessageSquareHeart', component: MessageSquareHeart },
    { name: 'MessageSquareLock', component: MessageSquareLock },
    { name: 'MessageSquareMore', component: MessageSquareMore },
    { name: 'MessageSquareOff', component: MessageSquareOff },
    { name: 'MessageSquarePlus', component: MessageSquarePlus },
    { name: 'MessageSquareQuote', component: MessageSquareQuote },
    { name: 'MessageSquareReply', component: MessageSquareReply },
    { name: 'MessageSquareShare', component: MessageSquareShare },
    { name: 'MessageSquareText', component: MessageSquareText },
    { name: 'MessageSquareWarning', component: MessageSquareWarning },
    { name: 'MessageSquareX', component: MessageSquareX },
    { name: 'MessagesSquare', component: MessagesSquare },
    { name: 'Mic', component: Mic },
    { name: 'Mic2', component: Mic2 },
    { name: 'MicOff', component: MicOff },
    { name: 'MicVocal', component: MicVocal },
    { name: 'Microchip', component: Microchip },
    { name: 'Microwave', component: Microwave },
    { name: 'Milestone', component: Milestone },
    { name: 'Milk', component: Milk },
    { name: 'MilkOff', component: MilkOff },
    { name: 'Minimize', component: Minimize },
    { name: 'Minimize2', component: Minimize2 },
    { name: 'Minus', component: Minus },
    { name: 'MinusCircle', component: MinusCircle },
    { name: 'MinusSquare', component: MinusSquare },
    { name: 'MonitorCheck', component: MonitorCheck },
    { name: 'MonitorCog', component: MonitorCog },
    { name: 'MonitorDot', component: MonitorDot },
    { name: 'MonitorDown', component: MonitorDown },
    { name: 'MonitorOff', component: MonitorOff },
    { name: 'MonitorPause', component: MonitorPause },
    { name: 'MonitorPlay', component: MonitorPlay },
    { name: 'MonitorSmartphone', component: MonitorSmartphone },
    { name: 'MonitorSpeaker', component: MonitorSpeaker },
    { name: 'MonitorStop', component: MonitorStop },
    { name: 'MonitorUp', component: MonitorUp },
    { name: 'MonitorX', component: MonitorX },
    { name: 'MoonStar', component: MoonStar },
    { name: 'MoreHorizontal', component: MoreHorizontal },
    { name: 'MoreVertical', component: MoreVertical },
    { name: 'MountainSnow', component: MountainSnow },
    { name: 'Mouse', component: Mouse },
    { name: 'MouseOff', component: MouseOff },
    { name: 'MousePointer', component: MousePointer },
    { name: 'MousePointer2', component: MousePointer2 },
    { name: 'MousePointerBan', component: MousePointerBan },
    { name: 'MousePointerClick', component: MousePointerClick },
    { name: 'Move', component: Move },
    { name: 'Move3d', component: Move3d },
    { name: 'MoveDiagonal', component: MoveDiagonal },
    { name: 'MoveDiagonal2', component: MoveDiagonal2 },
    { name: 'MoveDown', component: MoveDown },
    { name: 'MoveDownLeft', component: MoveDownLeft },
    { name: 'MoveDownRight', component: MoveDownRight },
    { name: 'MoveHorizontal', component: MoveHorizontal },
    { name: 'MoveLeft', component: MoveLeft },
    { name: 'MoveRight', component: MoveRight },
    { name: 'MoveUp', component: MoveUp },
    { name: 'MoveUpLeft', component: MoveUpLeft },
    { name: 'MoveUpRight', component: MoveUpRight },
    { name: 'MoveVertical', component: MoveVertical },
    { name: 'Music2', component: Music2 },
    { name: 'Music3', component: Music3 },
    { name: 'Music4', component: Music4 },
    { name: 'Navigation', component: Navigation },
    { name: 'Navigation2', component: Navigation2 },
    { name: 'NavigationOff', component: NavigationOff },
    { name: 'Nfc', component: Nfc },
    { name: 'NotebookPen', component: NotebookPen },
    { name: 'NotebookTabs', component: NotebookTabs },
    { name: 'NotebookText', component: NotebookText },
    { name: 'NotepadText', component: NotepadText },
    { name: 'NotepadTextDashed', component: NotepadTextDashed },
    { name: 'Nut', component: Nut },
    { name: 'OctagonAlert', component: OctagonAlert },
    { name: 'OctagonMinus', component: OctagonMinus },
    { name: 'OctagonPause', component: OctagonPause },
    { name: 'OctagonX', component: OctagonX },
    { name: 'Option', component: Option },
    { name: 'Orbit', component: Orbit },
    { name: 'Origami', component: Origami },
    { name: 'Package2', component: Package2 },
    { name: 'PackageCheck', component: PackageCheck },
    { name: 'PackageMinus', component: PackageMinus },
    { name: 'PackageOpen', component: PackageOpen },
    { name: 'PackagePlus', component: PackagePlus },
    { name: 'PackageSearch', component: PackageSearch },
    { name: 'PackageX', component: PackageX },
    { name: 'PaintBucket', component: PaintBucket },
    { name: 'PaintRoller', component: PaintRoller },
    { name: 'Paintbrush2', component: Paintbrush2 },
    { name: 'PanelBottom', component: PanelBottom },
    { name: 'PanelBottomClose', component: PanelBottomClose },
    { name: 'PanelBottomDashed', component: PanelBottomDashed },
    { name: 'PanelBottomOpen', component: PanelBottomOpen },
    { name: 'PanelLeft', component: PanelLeft },
    { name: 'PanelLeftClose', component: PanelLeftClose },
    { name: 'PanelLeftDashed', component: PanelLeftDashed },
    { name: 'PanelLeftOpen', component: PanelLeftOpen },
    { name: 'PanelRight', component: PanelRight },
    { name: 'PanelRightClose', component: PanelRightClose },
    { name: 'PanelRightDashed', component: PanelRightDashed },
    { name: 'PanelRightOpen', component: PanelRightOpen },
    { name: 'PanelTop', component: PanelTop },
    { name: 'PanelTopClose', component: PanelTopClose },
    { name: 'PanelTopDashed', component: PanelTopDashed },
    { name: 'PanelTopOpen', component: PanelTopOpen },
    { name: 'PanelsLeftBottom', component: PanelsLeftBottom },
    { name: 'PanelsRightBottom', component: PanelsRightBottom },
    { name: 'PanelsTopLeft', component: PanelsTopLeft },
    { name: 'Parentheses', component: Parentheses },
    { name: 'ParkingMeter', component: ParkingMeter },
    { name: 'PartyPopper', component: PartyPopper },
    { name: 'Pause', component: Pause },
    { name: 'PauseCircle', component: PauseCircle },
    { name: 'PawPrint', component: PawPrint },
    { name: 'PcCase', component: PcCase },
    { name: 'Pen', component: Pen },
    { name: 'PenLine', component: PenLine },
    { name: 'PenOff', component: PenOff },
    { name: 'Pencil', component: Pencil },
    { name: 'PencilLine', component: PencilLine },
    { name: 'PencilOff', component: PencilOff },
    { name: 'PencilRuler', component: PencilRuler },
    { name: 'Pentagon', component: Pentagon },
    { name: 'PercentCircle', component: PercentCircle },
    { name: 'PercentDiamond', component: PercentDiamond },
    { name: 'PercentSquare', component: PercentSquare },
    { name: 'PersonStanding', component: PersonStanding },
    { name: 'PhilippinePeso', component: PhilippinePeso },
    { name: 'PhoneCall', component: PhoneCall },
    { name: 'PhoneForwarded', component: PhoneForwarded },
    { name: 'PhoneIncoming', component: PhoneIncoming },
    { name: 'PhoneMissed', component: PhoneMissed },
    { name: 'PhoneOff', component: PhoneOff },
    { name: 'PhoneOutgoing', component: PhoneOutgoing },
    { name: 'Pi', component: Pi },
    { name: 'PiSquare', component: PiSquare },
    { name: 'Piano', component: Piano },
    { name: 'Pickaxe', component: Pickaxe },
    { name: 'PictureInPicture', component: PictureInPicture },
    { name: 'PictureInPicture2', component: PictureInPicture2 },
    { name: 'PiggyBank', component: PiggyBank },
    { name: 'Pilcrow', component: Pilcrow },
    { name: 'PilcrowLeft', component: PilcrowLeft },
    { name: 'PilcrowRight', component: PilcrowRight },
    { name: 'PilcrowSquare', component: PilcrowSquare },
    { name: 'Pill', component: Pill },
    { name: 'PillBottle', component: PillBottle },
    { name: 'Pin', component: Pin },
    { name: 'PinOff', component: PinOff },
    { name: 'Pipette', component: Pipette },
    { name: 'PlaneLanding', component: PlaneLanding },
    { name: 'PlaneTakeoff', component: PlaneTakeoff },
    { name: 'Play', component: Play },
    { name: 'PlayCircle', component: PlayCircle },
    { name: 'PlaySquare', component: PlaySquare },
    { name: 'Plug2', component: Plug2 },
    { name: 'PlugZap', component: PlugZap },
    { name: 'PlugZap2', component: PlugZap2 },
    { name: 'PlusCircle', component: PlusCircle },
    { name: 'PlusSquare', component: PlusSquare },
    { name: 'Pocket', component: Pocket },
    { name: 'PocketKnife', component: PocketKnife },
    { name: 'Pointer', component: Pointer },
    { name: 'PointerOff', component: PointerOff },
    { name: 'Popcorn', component: Popcorn },
    { name: 'Popsicle', component: Popsicle },
    { name: 'PoundSterling', component: PoundSterling },
    { name: 'Power', component: Power },
    { name: 'PowerCircle', component: PowerCircle },
    { name: 'PowerOff', component: PowerOff },
    { name: 'PowerSquare', component: PowerSquare },
    { name: 'Presentation', component: Presentation },
    { name: 'Projector', component: Projector },
    { name: 'Proportions', component: Proportions },
    { name: 'Pyramid', component: Pyramid },
    { name: 'Quote', component: Quote },
    { name: 'Rabbit', component: Rabbit },
    { name: 'Radar', component: Radar },
    { name: 'Radiation', component: Radiation },
    { name: 'Radical', component: Radical },
    { name: 'RadioReceiver', component: RadioReceiver },
    { name: 'RadioTower', component: RadioTower },
    { name: 'Radius', component: Radius },
    { name: 'RailSymbol', component: RailSymbol },
    { name: 'Rainbow', component: Rainbow },
    { name: 'Rat', component: Rat },
    { name: 'Ratio', component: Ratio },
    { name: 'Receipt', component: Receipt },
    { name: 'ReceiptCent', component: ReceiptCent },
    { name: 'ReceiptEuro', component: ReceiptEuro },
    { name: 'ReceiptIndianRupee', component: ReceiptIndianRupee },
    { name: 'ReceiptJapaneseYen', component: ReceiptJapaneseYen },
    { name: 'ReceiptPoundSterling', component: ReceiptPoundSterling },
    { name: 'ReceiptRussianRuble', component: ReceiptRussianRuble },
    { name: 'ReceiptSwissFranc', component: ReceiptSwissFranc },
    { name: 'ReceiptText', component: ReceiptText },
    { name: 'RectangleEllipsis', component: RectangleEllipsis },
    { name: 'RectangleHorizontal', component: RectangleHorizontal },
    { name: 'RectangleVertical', component: RectangleVertical },
    { name: 'Recycle', component: Recycle },
    { name: 'Redo', component: Redo },
    { name: 'Redo2', component: Redo2 },
    { name: 'RefreshCcw', component: RefreshCcw },
    { name: 'RefreshCcwDot', component: RefreshCcwDot },
    { name: 'RefreshCw', component: RefreshCw },
    { name: 'RefreshCwOff', component: RefreshCwOff },
    { name: 'Refrigerator', component: Refrigerator },
    { name: 'Regex', component: Regex },
    { name: 'RemoveFormatting', component: RemoveFormatting },
    { name: 'Repeat', component: Repeat },
    { name: 'Repeat1', component: Repeat1 },
    { name: 'Repeat2', component: Repeat2 },
    { name: 'Replace', component: Replace },
    { name: 'ReplaceAll', component: ReplaceAll },
    { name: 'Reply', component: Reply },
    { name: 'ReplyAll', component: ReplyAll },
    { name: 'Rewind', component: Rewind },
    { name: 'Ribbon', component: Ribbon },
    { name: 'RockingChair', component: RockingChair },
    { name: 'RollerCoaster', component: RollerCoaster },
    { name: 'Rotate3d', component: Rotate3d },
    { name: 'RotateCcw', component: RotateCcw },
    { name: 'RotateCcwSquare', component: RotateCcwSquare },
    { name: 'RotateCw', component: RotateCw },
    { name: 'RotateCwSquare', component: RotateCwSquare },
    { name: 'Route', component: Route },
    { name: 'RouteOff', component: RouteOff },
    { name: 'Router', component: Router },
    { name: 'Rows2', component: Rows2 },
    { name: 'Rows3', component: Rows3 },
    { name: 'Rows4', component: Rows4 },
    { name: 'Rss', component: Rss },
    { name: 'RussianRuble', component: RussianRuble },
    { name: 'Sailboat', component: Sailboat },
    { name: 'Salad', component: Salad },
    { name: 'Sandwich', component: Sandwich },
    { name: 'Satellite', component: Satellite },
    { name: 'SatelliteDish', component: SatelliteDish },
    { name: 'Save', component: Save },
    { name: 'SaveAll', component: SaveAll },
    { name: 'SaveOff', component: SaveOff },
    { name: 'Scale3d', component: Scale3d },
    { name: 'Scaling', component: Scaling },
    { name: 'Scan', component: Scan },
    { name: 'ScanBarcode', component: ScanBarcode },
    { name: 'ScanEye', component: ScanEye },
    { name: 'ScanFace', component: ScanFace },
    { name: 'ScanLine', component: ScanLine },
    { name: 'ScanQrCode', component: ScanQrCode },
    { name: 'ScanSearch', component: ScanSearch },
    { name: 'ScanText', component: ScanText },
    { name: 'ScatterChart', component: ScatterChart },
    { name: 'School', component: School },
    { name: 'School2', component: School2 },
    { name: 'ScissorsLineDashed', component: ScissorsLineDashed },
    { name: 'ScissorsSquare', component: ScissorsSquare },
    { name: 'ScissorsSquareDashedBottom', component: ScissorsSquareDashedBottom },
    { name: 'ScreenShare', component: ScreenShare },
    { name: 'ScreenShareOff', component: ScreenShareOff },
    { name: 'Scroll', component: Scroll },
    { name: 'ScrollText', component: ScrollText },
    { name: 'SearchCheck', component: SearchCheck },
    { name: 'SearchCode', component: SearchCode },
    { name: 'SearchSlash', component: SearchSlash },
    { name: 'SearchX', component: SearchX },
    { name: 'Section', component: Section },
    { name: 'Send', component: Send },
    { name: 'SendHorizontal', component: SendHorizontal },
    { name: 'SendToBack', component: SendToBack },
    { name: 'SeparatorHorizontal', component: SeparatorHorizontal },
    { name: 'SeparatorVertical', component: SeparatorVertical },
    { name: 'ServerCog', component: ServerCog },
    { name: 'ServerCrash', component: ServerCrash },
    { name: 'ServerOff', component: ServerOff },
    { name: 'Settings2', component: Settings2 },
    { name: 'Shapes', component: Shapes },
    { name: 'Share', component: Share },
    { name: 'Sheet', component: Sheet },
    { name: 'Shell', component: Shell },
    { name: 'ShieldAlert', component: ShieldAlert },
    { name: 'ShieldBan', component: ShieldBan },
    { name: 'ShieldEllipsis', component: ShieldEllipsis },
    { name: 'ShieldHalf', component: ShieldHalf },
    { name: 'ShieldMinus', component: ShieldMinus },
    { name: 'ShieldOff', component: ShieldOff },
    { name: 'ShieldPlus', component: ShieldPlus },
    { name: 'ShieldQuestion', component: ShieldQuestion },
    { name: 'ShieldX', component: ShieldX },
    { name: 'Ship', component: Ship },
    { name: 'ShipWheel', component: ShipWheel },
    { name: 'Shirt', component: Shirt },
    { name: 'ShoppingBasket', component: ShoppingBasket },
    { name: 'Shovel', component: Shovel },
    { name: 'ShowerHead', component: ShowerHead },
    { name: 'Shrink', component: Shrink },
    { name: 'Shrub', component: Shrub },
    { name: 'Shuffle', component: Shuffle },
    { name: 'Sidebar', component: Sidebar },
    { name: 'SidebarClose', component: SidebarClose },
    { name: 'SidebarOpen', component: SidebarOpen },
    { name: 'Sigma', component: Sigma },
    { name: 'Signal', component: Signal },
    { name: 'SignalHigh', component: SignalHigh },
    { name: 'SignalLow', component: SignalLow },
    { name: 'SignalMedium', component: SignalMedium },
    { name: 'SignalZero', component: SignalZero },
    { name: 'Signature', component: Signature },
    { name: 'SignpostBig', component: SignpostBig },
    { name: 'Siren', component: Siren },
    { name: 'SkipBack', component: SkipBack },
    { name: 'SkipForward', component: SkipForward },
    { name: 'Skull', component: Skull },
    { name: 'Slash', component: Slash },
    { name: 'Slice', component: Slice },
    { name: 'SlidersHorizontal', component: SlidersHorizontal },
    { name: 'SlidersVertical', component: SlidersVertical },
    { name: 'SmartphoneCharging', component: SmartphoneCharging },
    { name: 'SmartphoneNfc', component: SmartphoneNfc },
    { name: 'SmilePlus', component: SmilePlus },
    { name: 'Snail', component: Snail },
    { name: 'Snowflake', component: Snowflake },
    { name: 'Sofa', component: Sofa },
    { name: 'SortAsc', component: SortAsc },
    { name: 'SortDesc', component: SortDesc },
    { name: 'Soup', component: Soup },
    { name: 'Space', component: Space },
    { name: 'Spade', component: Spade },
    { name: 'Sparkle', component: Sparkle },
    { name: 'Speech', component: Speech },
    { name: 'SpellCheck', component: SpellCheck },
    { name: 'SpellCheck2', component: SpellCheck2 },
    { name: 'Spline', component: Spline },
    { name: 'Split', component: Split },
    { name: 'SprayCan', component: SprayCan },
    { name: 'Sprout', component: Sprout },
    { name: 'Square', component: Square },
    { name: 'SquareActivity', component: SquareActivity },
    { name: 'SquareArrowDown', component: SquareArrowDown },
    { name: 'SquareArrowDownLeft', component: SquareArrowDownLeft },
    { name: 'SquareArrowDownRight', component: SquareArrowDownRight },
    { name: 'SquareArrowLeft', component: SquareArrowLeft },
    { name: 'SquareArrowOutDownLeft', component: SquareArrowOutDownLeft },
    { name: 'SquareArrowOutDownRight', component: SquareArrowOutDownRight },
    { name: 'SquareArrowOutUpLeft', component: SquareArrowOutUpLeft },
    { name: 'SquareArrowOutUpRight', component: SquareArrowOutUpRight },
    { name: 'SquareArrowRight', component: SquareArrowRight },
    { name: 'SquareArrowUp', component: SquareArrowUp },
    { name: 'SquareArrowUpLeft', component: SquareArrowUpLeft },
    { name: 'SquareArrowUpRight', component: SquareArrowUpRight },
    { name: 'SquareAsterisk', component: SquareAsterisk },
    { name: 'SquareBottomDashedScissors', component: SquareBottomDashedScissors },
    { name: 'SquareChartGantt', component: SquareChartGantt },
    { name: 'SquareCheck', component: SquareCheck },
    { name: 'SquareCheckBig', component: SquareCheckBig },
    { name: 'SquareChevronDown', component: SquareChevronDown },
    { name: 'SquareChevronLeft', component: SquareChevronLeft },
    { name: 'SquareChevronRight', component: SquareChevronRight },
    { name: 'SquareChevronUp', component: SquareChevronUp },
    { name: 'SquareCode', component: SquareCode },
    { name: 'SquareDashedBottom', component: SquareDashedBottom },
    { name: 'SquareDashedBottomCode', component: SquareDashedBottomCode },
    { name: 'SquareDashedKanban', component: SquareDashedKanban },
    { name: 'SquareDashedMousePointer', component: SquareDashedMousePointer },
    { name: 'SquareDivide', component: SquareDivide },
    { name: 'SquareDot', component: SquareDot },
    { name: 'SquareEqual', component: SquareEqual },
    { name: 'SquareFunction', component: SquareFunction },
    { name: 'SquareGanttChart', component: SquareGanttChart },
    { name: 'SquareKanban', component: SquareKanban },
    { name: 'SquareLibrary', component: SquareLibrary },
    { name: 'SquareM', component: SquareM },
    { name: 'SquareMenu', component: SquareMenu },
    { name: 'SquareMinus', component: SquareMinus },
    { name: 'SquareMousePointer', component: SquareMousePointer },
    { name: 'SquareParking', component: SquareParking },
    { name: 'SquareParkingOff', component: SquareParkingOff },
    { name: 'SquarePen', component: SquarePen },
    { name: 'SquarePercent', component: SquarePercent },
    { name: 'SquarePi', component: SquarePi },
    { name: 'SquarePilcrow', component: SquarePilcrow },
    { name: 'SquarePlay', component: SquarePlay },
    { name: 'SquarePlus', component: SquarePlus },
    { name: 'SquarePower', component: SquarePower },
    { name: 'SquareRadical', component: SquareRadical },
    { name: 'SquareScissors', component: SquareScissors },
    { name: 'SquareSigma', component: SquareSigma },
    { name: 'SquareSlash', component: SquareSlash },
    { name: 'SquareSplitHorizontal', component: SquareSplitHorizontal },
    { name: 'SquareSplitVertical', component: SquareSplitVertical },
    { name: 'SquareSquare', component: SquareSquare },
    { name: 'SquareStack', component: SquareStack },
    { name: 'SquareTerminal', component: SquareTerminal },
    { name: 'SquareUser', component: SquareUser },
    { name: 'SquareUserRound', component: SquareUserRound },
    { name: 'SquareX', component: SquareX },
    { name: 'Squircle', component: Squircle },
    { name: 'Squirrel', component: Squirrel },
    { name: 'Stamp', component: Stamp },
    { name: 'StarHalf', component: StarHalf },
    { name: 'StarOff', component: StarOff },
    { name: 'StepBack', component: StepBack },
    { name: 'StepForward', component: StepForward },
    { name: 'Sticker', component: Sticker },
    { name: 'StickyNote', component: StickyNote },
    { name: 'Store', component: Store },
    { name: 'StretchHorizontal', component: StretchHorizontal },
    { name: 'StretchVertical', component: StretchVertical },
    { name: 'Strikethrough', component: Strikethrough },
    { name: 'Subscript', component: Subscript },
    { name: 'SunDim', component: SunDim },
    { name: 'SunMedium', component: SunMedium },
    { name: 'SunMoon', component: SunMoon },
    { name: 'SunSnow', component: SunSnow },
    { name: 'Sunrise', component: Sunrise },
    { name: 'Sunset', component: Sunset },
    { name: 'Superscript', component: Superscript },
    { name: 'SwatchBook', component: SwatchBook },
    { name: 'SwissFranc', component: SwissFranc },
    { name: 'SwitchCamera', component: SwitchCamera },
    { name: 'Swords', component: Swords },
    { name: 'Syringe', component: Syringe },
    { name: 'Table', component: Table },
    { name: 'Table2', component: Table2 },
    { name: 'TableCellsMerge', component: TableCellsMerge },
    { name: 'TableCellsSplit', component: TableCellsSplit },
    { name: 'TableColumnsSplit', component: TableColumnsSplit },
    { name: 'TableOfContents', component: TableOfContents },
    { name: 'TableProperties', component: TableProperties },
    { name: 'TableRowsSplit', component: TableRowsSplit },
    { name: 'Tablet', component: Tablet },
    { name: 'TabletSmartphone', component: TabletSmartphone },
    { name: 'Tablets', component: Tablets },
    { name: 'Tags', component: Tags },
    { name: 'Tally1', component: Tally1 },
    { name: 'Tally2', component: Tally2 },
    { name: 'Tally3', component: Tally3 },
    { name: 'Tally4', component: Tally4 },
    { name: 'Tally5', component: Tally5 },
    { name: 'Tangent', component: Tangent },
    { name: 'Tent', component: Tent },
    { name: 'TentTree', component: TentTree },
    { name: 'TerminalSquare', component: TerminalSquare },
    { name: 'TestTube', component: TestTube },
    { name: 'TestTube2', component: TestTube2 },
    { name: 'TestTubes', component: TestTubes },
    { name: 'Text', component: Text },
    { name: 'TextCursor', component: TextCursor },
    { name: 'TextCursorInput', component: TextCursorInput },
    { name: 'TextQuote', component: TextQuote },
    { name: 'TextSearch', component: TextSearch },
    { name: 'TextSelect', component: TextSelect },
    { name: 'Theater', component: Theater },
    { name: 'Thermometer', component: Thermometer },
    { name: 'ThermometerSnowflake', component: ThermometerSnowflake },
    { name: 'ThermometerSun', component: ThermometerSun },
    { name: 'ThumbsDown', component: ThumbsDown },
    { name: 'Ticket', component: Ticket },
    { name: 'TicketCheck', component: TicketCheck },
    { name: 'TicketMinus', component: TicketMinus },
    { name: 'TicketPercent', component: TicketPercent },
    { name: 'TicketPlus', component: TicketPlus },
    { name: 'TicketSlash', component: TicketSlash },
    { name: 'TicketX', component: TicketX },
    { name: 'TicketsPlane', component: TicketsPlane },
    { name: 'TimerOff', component: TimerOff },
    { name: 'TimerReset', component: TimerReset },
    { name: 'ToggleRight', component: ToggleRight },
    { name: 'Tornado', component: Tornado },
    { name: 'Torus', component: Torus },
    { name: 'Touchpad', component: Touchpad },
    { name: 'TouchpadOff', component: TouchpadOff },
    { name: 'TowerControl', component: TowerControl },
    { name: 'ToyBrick', component: ToyBrick },
    { name: 'Tractor', component: Tractor },
    { name: 'TrafficCone', component: TrafficCone },
    { name: 'Train', component: Train },
    { name: 'TrainFront', component: TrainFront },
    { name: 'TrainFrontTunnel', component: TrainFrontTunnel },
    { name: 'TrainTrack', component: TrainTrack },
    { name: 'TramFront', component: TramFront },
    { name: 'Trash2', component: Trash2 },
    { name: 'TreeDeciduous', component: TreeDeciduous },
    { name: 'TreePalm', component: TreePalm },
    { name: 'TreePine', component: TreePine },
    { name: 'Trees', component: Trees },
    { name: 'Trello', component: Trello },
    { name: 'TrendingDown', component: TrendingDown },
    { name: 'Triangle', component: Triangle },
    { name: 'TriangleAlert', component: TriangleAlert },
    { name: 'TriangleRight', component: TriangleRight },
    { name: 'Turtle', component: Turtle },
    { name: 'Tv2', component: Tv2 },
    { name: 'TvMinimal', component: TvMinimal },
    { name: 'TvMinimalPlay', component: TvMinimalPlay },
    { name: 'Twitch', component: Twitch },
    { name: 'Twitter', component: Twitter },
    { name: 'Type', component: Type },
    { name: 'TypeOutline', component: TypeOutline },
    { name: 'UmbrellaOff', component: UmbrellaOff },
    { name: 'Underline', component: Underline },
    { name: 'Undo', component: Undo },
    { name: 'Undo2', component: Undo2 },
    { name: 'UnfoldHorizontal', component: UnfoldHorizontal },
    { name: 'UnfoldVertical', component: UnfoldVertical },
    { name: 'Ungroup', component: Ungroup },
    { name: 'University', component: University },
    { name: 'Unlink', component: Unlink },
    { name: 'Unlink2', component: Unlink2 },
    { name: 'Unplug', component: Unplug },
    { name: 'UploadCloud', component: UploadCloud },
    { name: 'Usb', component: Usb },
    { name: 'User2', component: User2 },
    { name: 'UserCheck', component: UserCheck },
    { name: 'UserCheck2', component: UserCheck2 },
    { name: 'UserCircle', component: UserCircle },
    { name: 'UserCircle2', component: UserCircle2 },
    { name: 'UserCog', component: UserCog },
    { name: 'UserCog2', component: UserCog2 },
    { name: 'UserMinus', component: UserMinus },
    { name: 'UserMinus2', component: UserMinus2 },
    { name: 'UserPen', component: UserPen },
    { name: 'UserPlus', component: UserPlus },
    { name: 'UserPlus2', component: UserPlus2 },
    { name: 'UserRound', component: UserRound },
    { name: 'UserRoundCheck', component: UserRoundCheck },
    { name: 'UserRoundCog', component: UserRoundCog },
    { name: 'UserRoundMinus', component: UserRoundMinus },
    { name: 'UserRoundPen', component: UserRoundPen },
    { name: 'UserRoundPlus', component: UserRoundPlus },
    { name: 'UserRoundSearch', component: UserRoundSearch },
    { name: 'UserRoundX', component: UserRoundX },
    { name: 'UserSearch', component: UserSearch },
    { name: 'UserX', component: UserX },
    { name: 'UserX2', component: UserX2 },
    { name: 'Users2', component: Users2 },
    { name: 'UsersRound', component: UsersRound },
    { name: 'Utensils', component: Utensils },
    { name: 'UtensilsCrossed', component: UtensilsCrossed },
    { name: 'UtilityPole', component: UtilityPole },
    { name: 'Variable', component: Variable },
    { name: 'Vault', component: Vault },
    { name: 'Vegan', component: Vegan },
    { name: 'VenetianMask', component: VenetianMask },
    { name: 'Vibrate', component: Vibrate },
    { name: 'VibrateOff', component: VibrateOff },
    { name: 'VideoOff', component: VideoOff },
    { name: 'Videotape', component: Videotape },
    { name: 'View', component: View },
    { name: 'Volleyball', component: Volleyball },
    { name: 'Volume', component: Volume },
    { name: 'Volume1', component: Volume1 },
    { name: 'VolumeOff', component: VolumeOff },
    { name: 'VolumeX', component: VolumeX },
    { name: 'Vote', component: Vote },
    { name: 'Wallet2', component: Wallet2 },
    { name: 'WalletCards', component: WalletCards },
    { name: 'WalletMinimal', component: WalletMinimal },
    { name: 'Wallpaper', component: Wallpaper },
    { name: 'Wand', component: Wand },
    { name: 'Wand2', component: Wand2 },
    { name: 'WandSparkles', component: WandSparkles },
    { name: 'Warehouse', component: Warehouse },
    { name: 'WashingMachine', component: WashingMachine },
    { name: 'Waves', component: Waves },
    { name: 'Waypoints', component: Waypoints },
    { name: 'Webcam', component: Webcam },
    { name: 'Webhook', component: Webhook },
    { name: 'Weight', component: Weight },
    { name: 'Wheat', component: Wheat },
    { name: 'WheatOff', component: WheatOff },
    { name: 'WholeWord', component: WholeWord },
    { name: 'WifiHigh', component: WifiHigh },
    { name: 'WifiLow', component: WifiLow },
    { name: 'WifiOff', component: WifiOff },
    { name: 'WifiZero', component: WifiZero },
    { name: 'Wine', component: Wine },
    { name: 'WineOff', component: WineOff },
    { name: 'Workflow', component: Workflow },
    { name: 'Worm', component: Worm },
    { name: 'WrapText', component: WrapText },
    { name: 'XCircle', component: XCircle },
    { name: 'XOctagon', component: XOctagon },
    { name: 'XSquare', component: XSquare },
    { name: 'ZapOff', component: ZapOff },
    { name: 'ZoomIn', component: ZoomIn },
    { name: 'ZoomOut', component: ZoomOut },
  ], []);

  const filteredIcons = useMemo(() => {
    if (!searchTerm) return availableIcons;
    return availableIcons.filter(icon => 
      icon.name.toLowerCase().includes(searchTerm.toLowerCase())
    );
  }, [searchTerm, availableIcons]);

  const selectedIcon = availableIcons.find(icon => icon.name === value);
  const SelectedIconComponent = selectedIcon?.component || Package;

  const handleIconSelect = (iconName: string) => {
    onChange(iconName);
    setIsOpen(false);
    setSearchTerm('');
  };

  return (
    <div className="w-full">
      <Label>{label}</Label>
      <Popover open={isOpen} onOpenChange={setIsOpen}>
        <PopoverTrigger asChild>
          <Button 
            variant="outline" 
            className="w-full justify-start gap-2 h-10"
            type="button"
          >
            <SelectedIconComponent className="h-4 w-4" />
            <span>{selectedIcon?.name || 'Selecionar ícone'}</span>
          </Button>
        </PopoverTrigger>
        <PopoverContent 
          className="w-[340px] sm:w-[480px] md:w-[600px] lg:w-[800px] xl:w-[900px] p-4" 
          align="start"
          side="bottom"
          sideOffset={4}
        >
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <div className="text-sm font-medium">
                Selecione um ícone ({filteredIcons.length} de {availableIcons.length})
              </div>
            </div>
            
            <Input
              placeholder="Buscar ícone..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="h-9"
            />
            
            <ScrollArea className="h-[400px] md:h-[500px] lg:h-[600px]">
              <div className="grid grid-cols-6 sm:grid-cols-8 md:grid-cols-10 lg:grid-cols-14 xl:grid-cols-16 gap-1.5 p-1">
                {filteredIcons.map((icon) => {
                  const IconComponent = icon.component;
                  const isSelected = value === icon.name;
                  
                  return (
                    <Button
                      key={icon.name}
                      variant={isSelected ? "default" : "ghost"}
                      size="sm"
                      className="h-11 w-11 sm:h-12 sm:w-12 p-0 flex flex-col items-center justify-center"
                      onClick={() => handleIconSelect(icon.name)}
                      type="button"
                      title={icon.name}
                    >
                      <IconComponent className="h-5 w-5 sm:h-6 sm:w-6" />
                    </Button>
                  );
                })}
              </div>
            </ScrollArea>
            
            {selectedIcon && (
              <div className="flex items-center gap-2 pt-2 border-t">
                <Badge variant="secondary" className="gap-1">
                  <SelectedIconComponent className="h-3 w-3" />
                  {selectedIcon.name}
                </Badge>
              </div>
            )}
          </div>
        </PopoverContent>
      </Popover>
    </div>
  );
};

export default IconSelector;
